//
        // BLL/BOM [C#]
        // Business Object RigaFattura Extension
        //
        // Generated by MGen/Caffettiera
        // (C) 2008 Netical 
        //
        
        using System;
        using System.Collections;
        using System.Collections.Generic;
        using Caffettiera.CSharp.Common;
        using Caffettiera.CSharp.BLL;
        using Caffettiera.CSharp.BLL.BOM;
        
        
        namespace GenTest.BOM
        {
        
        public partial class RigaFattura : IRigaFatturaExt
		{
			
		}
		
        
        }
        
