/*
         * DDL
         * GenTest [MSSQL2005]
         *
         * Generated by MGen/Caffettiera
         * (C) 2008 Netical
         */
        
        USE GenTest
        ;
        
        /* Drop constraints and tables */
        
        IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('FK_Aggregated_Fattura_RigaFattura') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
        ALTER TABLE Fattura DROP CONSTRAINT FK_Aggregated_Fattura_RigaFattura
        ;
        
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Fattura') AND OBJECTPROPERTY(id, 'IsUserTable') = 1)
        DROP TABLE Fattura
        ;
        
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('RigaFattura') AND OBJECTPROPERTY(id, 'IsUserTable') = 1)
        DROP TABLE RigaFattura
        ;
        
        
        
        
        /* Tables */
        
        CREATE TABLE Fattura (
        Intestatario ntext NOT NULL,
Descrizione datetime NOT NULL,
Data nvarchar(11) NOT NULL,
Numero int NOT NULL,
ID Integer NOT NULL IDENTITY(1,1),
AggregatedRigaFatturaID Integer
        )
        ;
        
CREATE TABLE RigaFattura (
        Descrizione nchar NOT NULL,
Importo float NOT NULL,
ID Integer NOT NULL IDENTITY(1,1)
        )
        ;
        
        
        
        
        /* Constraints on Primary Keys */
        
        ALTER TABLE Fattura ADD CONSTRAINT PK_Fattura
	    PRIMARY KEY CLUSTERED (ID)
	    ;
	    
ALTER TABLE RigaFattura ADD CONSTRAINT PK_RigaFattura
	    PRIMARY KEY CLUSTERED (ID)
	    ;
	    
        
        
        
        /* Constraints on Foreign Keys */
        
        ALTER TABLE Fattura ADD CONSTRAINT FK_Aggregated_Fattura_RigaFattura
	    FOREIGN KEY (AggregatedRigaFatturaID) REFERENCES RigaFattura (ID)
	    ;
	    
        
