//
        // UI/WebUserControls [C#]
        // FatturaForm
        //
        // Generated by Caffettiera
        // (C) 2008 Netical 
        //
        
        using System;
        using System.Data;
        using System.Configuration;
        using System.Web;
        using System.Web.Security;
        using System.Web.UI;
        using System.Web.UI.WebControls;
        using System.Web.UI.WebControls.WebParts;
        using System.Web.UI.HtmlControls;
        using System.Collections.Generic;
        using Obout.Grid;
        using Caffettiera.CSharp.UI.WebUserControls.MVP;
        
        
        namespace GenTest.WebUserControls
        {
        
        public partial class FatturaFormFormView
        {
            protected global::Caffettiera.CSharp.UI.WebUserControls.MultiForm.MultiFormView FatturaFormControl;
        }
        
        
        }
        
