// Implementation file for parser generated by fsyacc
#light
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 2 "typarser.fsy"


open Caffettiera.FSharp.Generator.Tyabsyn


# 12 "typarser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | ABRA
  | AKET
  | SQBRA
  | SQKET
  | STRING
  | INT
  | BOOL
  | FLOAT
  | DATETIME
  | DECIMAL
  | CHAR
  | BO
  | BOA
  | COLON
  | VOID
  | COMMA
  | BINARY
  | EOF
  | NAT of (System.Int32)
  | ID of (string)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_ABRA
    | TOKEN_AKET
    | TOKEN_SQBRA
    | TOKEN_SQKET
    | TOKEN_STRING
    | TOKEN_INT
    | TOKEN_BOOL
    | TOKEN_FLOAT
    | TOKEN_DATETIME
    | TOKEN_DECIMAL
    | TOKEN_CHAR
    | TOKEN_BO
    | TOKEN_BOA
    | TOKEN_COLON
    | TOKEN_VOID
    | TOKEN_COMMA
    | TOKEN_BINARY
    | TOKEN_EOF
    | TOKEN_NAT
    | TOKEN_ID
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startret
    | NONTERM__startcomplex
    | NONTERM__startsimple
    | NONTERM_simple
    | NONTERM_complex
    | NONTERM_ret
    | NONTERM_simplety
    | NONTERM_complexty
    | NONTERM_special
    | NONTERM_retty

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | ABRA  -> 0 
  | AKET  -> 1 
  | SQBRA  -> 2 
  | SQKET  -> 3 
  | STRING  -> 4 
  | INT  -> 5 
  | BOOL  -> 6 
  | FLOAT  -> 7 
  | DATETIME  -> 8 
  | DECIMAL  -> 9 
  | CHAR  -> 10 
  | BO  -> 11 
  | BOA  -> 12 
  | COLON  -> 13 
  | VOID  -> 14 
  | COMMA  -> 15 
  | BINARY  -> 16 
  | EOF  -> 17 
  | NAT _ -> 18 
  | ID _ -> 19 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_ABRA 
  | 1 -> TOKEN_AKET 
  | 2 -> TOKEN_SQBRA 
  | 3 -> TOKEN_SQKET 
  | 4 -> TOKEN_STRING 
  | 5 -> TOKEN_INT 
  | 6 -> TOKEN_BOOL 
  | 7 -> TOKEN_FLOAT 
  | 8 -> TOKEN_DATETIME 
  | 9 -> TOKEN_DECIMAL 
  | 10 -> TOKEN_CHAR 
  | 11 -> TOKEN_BO 
  | 12 -> TOKEN_BOA 
  | 13 -> TOKEN_COLON 
  | 14 -> TOKEN_VOID 
  | 15 -> TOKEN_COMMA 
  | 16 -> TOKEN_BINARY 
  | 17 -> TOKEN_EOF 
  | 18 -> TOKEN_NAT 
  | 19 -> TOKEN_ID 
  | 22 -> TOKEN_end_of_input
  | 20 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startret 
    | 1 -> NONTERM__startcomplex 
    | 2 -> NONTERM__startsimple 
    | 3 -> NONTERM_simple 
    | 4 -> NONTERM_complex 
    | 5 -> NONTERM_ret 
    | 6 -> NONTERM_simplety 
    | 7 -> NONTERM_simplety 
    | 8 -> NONTERM_simplety 
    | 9 -> NONTERM_simplety 
    | 10 -> NONTERM_simplety 
    | 11 -> NONTERM_simplety 
    | 12 -> NONTERM_simplety 
    | 13 -> NONTERM_simplety 
    | 14 -> NONTERM_simplety 
    | 15 -> NONTERM_simplety 
    | 16 -> NONTERM_simplety 
    | 17 -> NONTERM_complexty 
    | 18 -> NONTERM_complexty 
    | 19 -> NONTERM_complexty 
    | 20 -> NONTERM_special 
    | 21 -> NONTERM_special 
    | 22 -> NONTERM_retty 
    | 23 -> NONTERM_retty 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 22 
let _fsyacc_tagOfErrorTerminal = 20

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | ABRA  -> "ABRA" 
  | AKET  -> "AKET" 
  | SQBRA  -> "SQBRA" 
  | SQKET  -> "SQKET" 
  | STRING  -> "STRING" 
  | INT  -> "INT" 
  | BOOL  -> "BOOL" 
  | FLOAT  -> "FLOAT" 
  | DATETIME  -> "DATETIME" 
  | DECIMAL  -> "DECIMAL" 
  | CHAR  -> "CHAR" 
  | BO  -> "BO" 
  | BOA  -> "BOA" 
  | COLON  -> "COLON" 
  | VOID  -> "VOID" 
  | COMMA  -> "COMMA" 
  | BINARY  -> "BINARY" 
  | EOF  -> "EOF" 
  | NAT _ -> "NAT" 
  | ID _ -> "ID" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | ABRA  -> (null : System.Object) 
  | AKET  -> (null : System.Object) 
  | SQBRA  -> (null : System.Object) 
  | SQKET  -> (null : System.Object) 
  | STRING  -> (null : System.Object) 
  | INT  -> (null : System.Object) 
  | BOOL  -> (null : System.Object) 
  | FLOAT  -> (null : System.Object) 
  | DATETIME  -> (null : System.Object) 
  | DECIMAL  -> (null : System.Object) 
  | CHAR  -> (null : System.Object) 
  | BO  -> (null : System.Object) 
  | BOA  -> (null : System.Object) 
  | COLON  -> (null : System.Object) 
  | VOID  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | BINARY  -> (null : System.Object) 
  | EOF  -> (null : System.Object) 
  | NAT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | ID _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 0us; 65535us; 0us; 65535us; 1us; 65535us; 4us; 5us; 1us; 65535us; 2us; 3us; 1us; 65535us; 0us; 1us; 4us; 65535us; 0us; 36us; 2us; 36us; 4us; 6us; 33us; 36us; 3us; 65535us; 0us; 40us; 2us; 8us; 33us; 34us; 3us; 65535us; 0us; 30us; 2us; 30us; 33us; 30us; 1us; 65535us; 0us; 10us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 2us; 3us; 5us; 7us; 9us; 14us; 18us; 22us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 1us; 1us; 2us; 1us; 2us; 1us; 3us; 1us; 3us; 1us; 4us; 1us; 4us; 1us; 5us; 1us; 5us; 2us; 6us; 7us; 1us; 7us; 1us; 7us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 12us; 1us; 13us; 1us; 14us; 2us; 14us; 18us; 2us; 15us; 16us; 1us; 16us; 1us; 16us; 1us; 16us; 1us; 16us; 1us; 16us; 1us; 17us; 1us; 17us; 1us; 17us; 1us; 18us; 1us; 18us; 1us; 18us; 1us; 19us; 1us; 20us; 1us; 21us; 1us; 22us; 1us; 23us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 14us; 16us; 18us; 20us; 22us; 24us; 27us; 29us; 31us; 33us; 35us; 37us; 39us; 41us; 43us; 45us; 47us; 50us; 53us; 55us; 57us; 59us; 61us; 63us; 65us; 67us; 69us; 71us; 73us; 75us; 77us; 79us; 81us; 83us; |]
let _fsyacc_action_rows = 41
let _fsyacc_actionTableElements = [|12us; 32768us; 4us; 12us; 5us; 16us; 6us; 17us; 7us; 18us; 8us; 20us; 9us; 24us; 10us; 19us; 11us; 37us; 12us; 38us; 14us; 39us; 16us; 21us; 19us; 23us; 0us; 49152us; 11us; 32768us; 4us; 12us; 5us; 16us; 6us; 17us; 7us; 18us; 8us; 20us; 9us; 24us; 10us; 19us; 11us; 37us; 12us; 38us; 16us; 21us; 19us; 23us; 0us; 49152us; 9us; 32768us; 4us; 12us; 5us; 16us; 6us; 17us; 7us; 18us; 8us; 20us; 9us; 24us; 10us; 19us; 16us; 21us; 19us; 22us; 0us; 49152us; 1us; 32768us; 17us; 7us; 0us; 16387us; 1us; 32768us; 17us; 9us; 0us; 16388us; 1us; 32768us; 17us; 11us; 0us; 16389us; 1us; 16390us; 2us; 13us; 1us; 32768us; 18us; 14us; 1us; 32768us; 3us; 15us; 0us; 16391us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 0us; 16396us; 0us; 16397us; 0us; 16398us; 1us; 16398us; 0us; 33us; 1us; 16399us; 2us; 25us; 1us; 32768us; 18us; 26us; 1us; 32768us; 15us; 27us; 1us; 32768us; 18us; 28us; 1us; 32768us; 3us; 29us; 0us; 16400us; 1us; 32768us; 13us; 31us; 1us; 32768us; 19us; 32us; 0us; 16401us; 11us; 32768us; 4us; 12us; 5us; 16us; 6us; 17us; 7us; 18us; 8us; 20us; 9us; 24us; 10us; 19us; 11us; 37us; 12us; 38us; 16us; 21us; 19us; 23us; 1us; 32768us; 1us; 35us; 0us; 16402us; 0us; 16403us; 0us; 16404us; 0us; 16405us; 0us; 16406us; 0us; 16407us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 13us; 14us; 26us; 27us; 37us; 38us; 40us; 41us; 43us; 44us; 46us; 47us; 49us; 51us; 53us; 54us; 55us; 56us; 57us; 58us; 59us; 60us; 61us; 63us; 65us; 67us; 69us; 71us; 73us; 74us; 76us; 78us; 79us; 91us; 93us; 94us; 95us; 96us; 97us; 98us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 2us; 2us; 2us; 1us; 4us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; 6us; 3us; 4us; 1us; 1us; 1us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 3us; 4us; 5us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 7us; 7us; 7us; 8us; 8us; 9us; 9us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 49152us; 65535us; 49152us; 65535us; 16387us; 65535us; 16388us; 65535us; 16389us; 65535us; 65535us; 65535us; 16391us; 16392us; 16393us; 16394us; 16395us; 16396us; 16397us; 16398us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16400us; 65535us; 65535us; 16401us; 65535us; 65535us; 16402us; 16403us; 16404us; 16405us; 16406us; 16407us; |]
let _fsyacc_reductions ()  =    [| 
# 213 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  ret )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startret));
# 222 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  complex )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startcomplex));
# 231 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  simple )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startsimple));
# 240 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'simplety)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 23 "typarser.fsy"
                      _1 
                   )
# 23 "typarser.fsy"
                 :  simple ));
# 251 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'complexty)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "typarser.fsy"
                      _1 
                   )
# 26 "typarser.fsy"
                 :  complex ));
# 262 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'retty)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "typarser.fsy"
                      _1 
                   )
# 29 "typarser.fsy"
                 :  ret ));
# 273 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "typarser.fsy"
                      String None 
                   )
# 32 "typarser.fsy"
                 : 'simplety));
# 283 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : System.Int32)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "typarser.fsy"
                      if _3 > 0 then String (Some _3) else raise (ParseError "variable string length cannot be zero") 
                   )
# 33 "typarser.fsy"
                 : 'simplety));
# 294 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "typarser.fsy"
                      Int 
                   )
# 35 "typarser.fsy"
                 : 'simplety));
# 304 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "typarser.fsy"
                      Bool 
                   )
# 36 "typarser.fsy"
                 : 'simplety));
# 314 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "typarser.fsy"
                      Float 
                   )
# 37 "typarser.fsy"
                 : 'simplety));
# 324 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "typarser.fsy"
                      Char 
                   )
# 38 "typarser.fsy"
                 : 'simplety));
# 334 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "typarser.fsy"
                      Datetime 
                   )
# 39 "typarser.fsy"
                 : 'simplety));
# 344 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "typarser.fsy"
                      Binary 
                   )
# 40 "typarser.fsy"
                 : 'simplety));
# 354 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "typarser.fsy"
                      Verbatim _1 
                   )
# 41 "typarser.fsy"
                 : 'simplety));
# 365 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 "typarser.fsy"
                      Decimal None 
                   )
# 43 "typarser.fsy"
                 : 'simplety));
# 375 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : System.Int32)) in
            let _5 = (let data = parseState.GetInput(5) in (Microsoft.FSharp.Core.Operators.unbox data : System.Int32)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 "typarser.fsy"
                      Decimal (Some (_3, _5)) 
                   )
# 44 "typarser.fsy"
                 : 'simplety));
# 387 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'special)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "typarser.fsy"
                      Special (_1, _3) 
                   )
# 47 "typarser.fsy"
                 : 'complexty));
# 399 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'complexty)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "typarser.fsy"
                      App (_1, _3) 
                   )
# 48 "typarser.fsy"
                 : 'complexty));
# 411 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'simplety)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "typarser.fsy"
                      Simple _1 
                   )
# 49 "typarser.fsy"
                 : 'complexty));
# 422 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "typarser.fsy"
                      Bo 
                   )
# 52 "typarser.fsy"
                 : 'special));
# 432 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "typarser.fsy"
                      Boa 
                   )
# 53 "typarser.fsy"
                 : 'special));
# 442 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "typarser.fsy"
                      Void 
                   )
# 56 "typarser.fsy"
                 : 'retty));
# 452 "typarser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'complexty)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "typarser.fsy"
                      Complex _1 
                   )
# 57 "typarser.fsy"
                 : 'retty));
|]
# 464 "typarser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 23;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let ret lexer lexbuf :  ret  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
let complex lexer lexbuf :  complex  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 2))
let simple lexer lexbuf :  simple  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 4))
