//
        // BLL [C#]
        // Fatturazione
        //
        // Generated by MGen/Caffettiera
        // (C) 2008 Netical 
        //
        
        using System;
        using System.Collections;
        using System.Collections.Generic;
        using Caffettiera.CSharp.Common;
        
        
        namespace GenTest.BLL
        {
        
        public interface Fatturazione
		{
			DateTime P2 { get; set; }
int P1 { get; set; }
			
			void F2(bool A, List<GenTest.BOM.Fattura> B, GenTest.BOAM.RigaFattura C);
ICollection<List<DateTime>> F1();
		}
		
        
        }
        
