//
        // BLL/BOAM [C#]
        // Business Object Avatar RigaFattura
        //
        // Generated by MGen/Caffettiera
        // (C) 2008 Netical 
        //
        
        using System;
        using System.Collections;
        using System.Collections.Generic;
        using Caffettiera.CSharp.Common;
        using Caffettiera.CSharp.BLL;
        
        
        namespace GenTest.BOAM
        {
        
        internal interface IRigaFatturaExt
		{
			int Lunghezza();
		}
		
public partial  class RigaFattura 
        {
        
			private int? uid;
            
            #region Constructors
            
            public RigaFattura()
            {
				uid = null;
            }
            
            protected internal RigaFattura(int uid)
            {
				this.uid = uid;
            }
            
            #endregion

            public static  RigaFattura Create()
            {
                return new RigaFattura();
            }

            public virtual bool IsValid()
            {
                return true;
            }
            
            public virtual int? UId
            {
                get { return uid; }
            }
              
            public  void SetPropertyByName<T>(string name, T x)
            {
                this.GetType().GetProperty(name, typeof(T)).SetValue(this, x, null);
            }

            public  void SetPropertyByNameFromString(string name, string x)
            {
                Type[] tys = { typeof(string) };
                object[] args = { x };
                var p = this.GetType().GetProperty(name);
                try
                {
                    p.SetValue(this, p.PropertyType.GetConstructor(tys).Invoke(args), null);
                }
                catch (System.ArgumentException e)
                {
                    throw new UnexpectedException(string.Format("type '{0}' does not provide a constructor from 'string'", p.PropertyType), e);
                }
            }

            public  T GetPropertyByName<T>(string name)
            {
                return (T)this.GetType().GetProperty(name, typeof(T)).GetValue(this, null);
            }                      
        
            private char _Descrizione;
        
        public char Descrizione
        {
            get { return _Descrizione; }
            set { _Descrizione = value; }
        }
        
private double _Importo;
        
        public double Importo
        {
            get { return _Importo; }
            set { _Importo = value; }
        }
        #region Fattura-to-RigaFattura Aggregation
        
        protected internal List<Fattura> _AggregationFattura = null;

        public List<Fattura> AggregationFattura
        {
            get { return _AggregationFattura; }
            
            set
            {
				if (_AggregationFattura != null)
					foreach(var x in _AggregationFattura) x._AggregatedRigaFattura = null;
				_AggregationFattura = value;
				if (value != null)
					foreach(var x in _AggregationFattura) x._AggregatedRigaFattura = this;
			}
        }
        
        
        #endregion
        
        }
        
        
        }
        
