
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Motore.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using GenTest.Entities.Validation;
#endregion

namespace GenTest.Entities
{
	///<summary>
	/// An object representation of the 'Motore' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class MotoreBase : EntityBase, IMotore, IEntityId<MotoreKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private MotoreEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private MotoreEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private MotoreEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Motore> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event MotoreEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MotoreEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="MotoreBase"/> instance.
		///</summary>
		public MotoreBase()
		{
			this.entityData = new MotoreEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="MotoreBase"/> instance.
		///</summary>
		///<param name="_descrizione"></param>
		///<param name="_aggregationMotoreID"></param>
		public MotoreBase(System.String _descrizione, System.Int32? _aggregationMotoreID)
		{
			this.entityData = new MotoreEntityData();
			this.backupData = null;

			this.Descrizione = _descrizione;
			this.AggregationMotoreID = _aggregationMotoreID;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Motore"/> instance.
		///</summary>
		///<param name="_descrizione"></param>
		///<param name="_aggregationMotoreID"></param>
		public static Motore CreateMotore(System.String _descrizione, System.Int32? _aggregationMotoreID)
		{
			Motore newMotore = new Motore();
			newMotore.Descrizione = _descrizione;
			newMotore.AggregationMotoreID = _aggregationMotoreID;
			return newMotore;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Descrizione property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public virtual System.String Descrizione
		{
			get
			{
				return this.entityData.Descrizione; 
			}
			
			set
			{
				if (this.entityData.Descrizione == value)
					return;
					
				OnColumnChanging(MotoreColumn.Descrizione, this.entityData.Descrizione);
				this.entityData.Descrizione = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MotoreColumn.Descrizione, this.entityData.Descrizione);
				OnPropertyChanged("Descrizione");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public override System.Int32 ID
		{
			get
			{
				return this.entityData.ID; 
			}
			
			set
			{
				if (this.entityData.ID == value)
					return;
					
				OnColumnChanging(MotoreColumn.ID, this.entityData.ID);
				this.entityData.ID = value;
				this.EntityId.ID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MotoreColumn.ID, this.entityData.ID);
				OnPropertyChanged("ID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AggregationMotoreID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsAggregationMotoreIDNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? AggregationMotoreID
		{
			get
			{
				return this.entityData.AggregationMotoreID; 
			}
			
			set
			{
				if (this.entityData.AggregationMotoreID == value)
					return;
					
				OnColumnChanging(MotoreColumn.AggregationMotoreID, this.entityData.AggregationMotoreID);
				this.entityData.AggregationMotoreID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MotoreColumn.AggregationMotoreID, this.entityData.AggregationMotoreID);
				OnPropertyChanged("AggregationMotoreID");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Motore"/>.
		/// </summary>
		/// <value>The source Motore for AggregationMotoreID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Motore AggregationMotoreIDSource
      	{
            get { return entityData.AggregationMotoreIDSource; }
            set { entityData.AggregationMotoreIDSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Motore objects
		///	which are related to this object through the relation FK_Aggregation_Motore_Motore
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Motore> MotoreCollection
		{
			get { return entityData.MotoreCollection; }
			set { entityData.MotoreCollection = value; }	
		}
	
		/// <summary>
		///	Holds a collection of Pistone objects
		///	which are related to this object through the relation FK_Composition_Pistone_Motore
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Pistone> PistoneCollection
		{
			get { return entityData.PistoneCollection; }
			set { entityData.PistoneCollection = value; }	
		}

		/// <summary>
		///	Holds a Macchina object
		///	which is related to this object through the relation Macchina
		/// </summary>
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Macchina Macchina
		{
			get { return entityData.Macchina; }
			set { entityData.Macchina = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Descrizione", "Descrizione"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Descrizione", "Descrizione", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Motore"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Descrizione", "ID", "AggregationMotoreID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as MotoreEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Motore) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Motore>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Motore);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Motore Entity 
		///</summary>
		protected virtual Motore Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Motore copy = new Motore();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Descrizione = this.Descrizione;
				copy.ID = this.ID;
				copy.AggregationMotoreID = this.AggregationMotoreID;
			
			if (this.AggregationMotoreIDSource != null && existingCopies.Contains(this.AggregationMotoreIDSource))
				copy.AggregationMotoreIDSource = existingCopies[this.AggregationMotoreIDSource] as Motore;
			else
				copy.AggregationMotoreIDSource = MakeCopyOf(this.AggregationMotoreIDSource, existingCopies) as Motore;
		
			//deep copy nested objects
			copy.MotoreCollection = (TList<Motore>) MakeCopyOf(this.MotoreCollection, existingCopies); 
			copy.PistoneCollection = (TList<Pistone>) MakeCopyOf(this.PistoneCollection, existingCopies); 
			copy.Macchina = (Macchina) MakeCopyOf(this.Macchina, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Motore Entity 
		///</summary>
		public virtual Motore Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Motore Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Motore DeepCopy()
		{
			return EntityHelper.Clone<Motore>(this as Motore);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as MotoreEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as MotoreEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(MotoreColumn column)
		{
			switch(column)
			{
					case MotoreColumn.Descrizione:
					return entityData.Descrizione != _originalData.Descrizione;
					case MotoreColumn.ID:
					return entityData.ID != _originalData.ID;
					case MotoreColumn.AggregationMotoreID:
					return entityData.AggregationMotoreID != _originalData.AggregationMotoreID;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Descrizione != _originalData.Descrizione;
			result = result || entityData.ID != _originalData.ID;
			result = result || entityData.AggregationMotoreID != _originalData.AggregationMotoreID;
			return result;
		}	
		
		///<summary>
		///  Returns a Motore Entity with the original data.
		///</summary>
		public Motore GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateMotore(
				_originalData.Descrizione,
				_originalData.AggregationMotoreID
				);
				
			return (Motore)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="MotoreBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is MotoreBase)
				return ValueEquals(this, (MotoreBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="MotoreBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Descrizione.GetHashCode() ^ 
					this.ID.GetHashCode() ^ 
					((this.AggregationMotoreID == null) ? string.Empty : this.AggregationMotoreID.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="MotoreBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(MotoreBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="MotoreBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="MotoreBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="MotoreBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(MotoreBase Object1, MotoreBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Descrizione != Object2.Descrizione)
				equal = false;
			if (Object1.ID != Object2.ID)
				equal = false;
			if ( Object1.AggregationMotoreID != null && Object2.AggregationMotoreID != null )
			{
				if (Object1.AggregationMotoreID != Object2.AggregationMotoreID)
					equal = false;
			}
			else if (Object1.AggregationMotoreID == null ^ Object2.AggregationMotoreID == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((MotoreBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static MotoreComparer GetComparer()
        {
            return new MotoreComparer();
        }
        */

        // Comparer delegates back to Motore
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Motore rhs, MotoreColumn which)
        {
            switch (which)
            {
            	
            	
            	case MotoreColumn.Descrizione:
            		return this.Descrizione.CompareTo(rhs.Descrizione);
            		
            		                 
            	
            	
            	case MotoreColumn.ID:
            		return this.ID.CompareTo(rhs.ID);
            		
            		                 
            	
            	
            	case MotoreColumn.AggregationMotoreID:
            		return this.AggregationMotoreID.Value.CompareTo(rhs.AggregationMotoreID.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<MotoreKey> Members
		
		// member variable for the EntityId property
		private MotoreKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual MotoreKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new MotoreKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Motore")
					.Append("|").Append( this.ID.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- Descrizione: {0}{3}- ID: {1}{3}- AggregationMotoreID: {2}{3}", 
				this.Descrizione,
				this.ID,
				(this.AggregationMotoreID == null) ? string.Empty : this.AggregationMotoreID.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Motore' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class MotoreEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// ID : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "Motore"</remarks>
			public System.Int32 ID;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Descrizione : 
		/// </summary>
		public System.String		  Descrizione = string.Empty;
		
		/// <summary>
		/// AggregationMotoreID : 
		/// </summary>
		public System.Int32?		  AggregationMotoreID = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Motore _aggregationMotoreIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Motore"/>.
		/// </summary>
		/// <value>The source Motore for AggregationMotoreID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Motore AggregationMotoreIDSource
      	{
            get { return this._aggregationMotoreIDSource; }
            set { this._aggregationMotoreIDSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region MotoreCollection
		
		private TList<Motore> _motoreAggregationMotoreID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _motoreAggregationMotoreID
		/// </summary>	
		public TList<Motore> MotoreCollection
		{
			get
			{
				if (_motoreAggregationMotoreID == null)
				{
				_motoreAggregationMotoreID = new TList<Motore>();
				}
	
				return _motoreAggregationMotoreID;
			}
			set { _motoreAggregationMotoreID = value; }
		}
		
		#endregion

		#region PistoneCollection
		
		private TList<Pistone> _pistoneCompositionMotoreID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pistoneCompositionMotoreID
		/// </summary>	
		public TList<Pistone> PistoneCollection
		{
			get
			{
				if (_pistoneCompositionMotoreID == null)
				{
				_pistoneCompositionMotoreID = new TList<Pistone>();
				}
	
				return _pistoneCompositionMotoreID;
			}
			set { _pistoneCompositionMotoreID = value; }
		}
		
		#endregion

		#region Macchina
		
		private Macchina _macchinaAssociationMotoreID;
		
		/// <summary>
		///	Holds a  Macchina entity object
		///	which is related to this object through the relation _macchinaAssociationMotoreID
		/// </summary>
		public Macchina Macchina
		{
			get {		return _macchinaAssociationMotoreID;		}
			set { 	_macchinaAssociationMotoreID = value; 	}
		}
		
		#endregion 

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			MotoreEntityData _tmp = new MotoreEntityData();
						
			_tmp.ID = this.ID;
			
			_tmp.Descrizione = this.Descrizione;
			_tmp.AggregationMotoreID = this.AggregationMotoreID;
			
			#region Source Parent Composite Entities
			if (this.AggregationMotoreIDSource != null)
				_tmp.AggregationMotoreIDSource = MakeCopyOf(this.AggregationMotoreIDSource) as Motore;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._motoreAggregationMotoreID != null)
				_tmp.MotoreCollection = (TList<Motore>) MakeCopyOf(this.MotoreCollection); 
			if (this._pistoneCompositionMotoreID != null)
				_tmp.PistoneCollection = (TList<Pistone>) MakeCopyOf(this.PistoneCollection); 
			if (this._macchinaAssociationMotoreID != null)
				_tmp.Macchina = (Macchina) MakeCopyOf(this.Macchina); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			MotoreEntityData _tmp = new MotoreEntityData();
						
			_tmp.ID = this.ID;
			
			_tmp.Descrizione = this.Descrizione;
			_tmp.AggregationMotoreID = this.AggregationMotoreID;
			
			#region Source Parent Composite Entities
			if (this.AggregationMotoreIDSource != null && existingCopies.Contains(this.AggregationMotoreIDSource))
				_tmp.AggregationMotoreIDSource = existingCopies[this.AggregationMotoreIDSource] as Motore;
			else
				_tmp.AggregationMotoreIDSource = MakeCopyOf(this.AggregationMotoreIDSource, existingCopies) as Motore;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.MotoreCollection = (TList<Motore>) MakeCopyOf(this.MotoreCollection, existingCopies); 
			_tmp.PistoneCollection = (TList<Pistone>) MakeCopyOf(this.PistoneCollection, existingCopies); 
			_tmp.Macchina = (Macchina) MakeCopyOf(this.Macchina, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MotoreColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(MotoreColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MotoreColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(MotoreColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MotoreColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(MotoreColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				MotoreEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new MotoreEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MotoreColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(MotoreColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				MotoreEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new MotoreEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region MotoreEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Motore"/> object.
	/// </remarks>
	public class MotoreEventArgs : System.EventArgs
	{
		private MotoreColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the MotoreEventArgs class.
		///</summary>
		public MotoreEventArgs(MotoreColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the MotoreEventArgs class.
		///</summary>
		public MotoreEventArgs(MotoreColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The MotoreColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="MotoreColumn" />
		public MotoreColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Motore related events.
	///</summary>
	public delegate void MotoreEventHandler(object sender, MotoreEventArgs e);
	
	#region MotoreComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class MotoreComparer : System.Collections.Generic.IComparer<Motore>
	{
		MotoreColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:MotoreComparer"/> class.
        /// </summary>
		public MotoreComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:MotoreComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public MotoreComparer(MotoreColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Motore"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Motore"/> to compare.</param>
        /// <param name="b">The second <c>Motore</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Motore a, Motore b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Motore entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Motore a, Motore b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public MotoreColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region MotoreKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Motore"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class MotoreKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the MotoreKey class.
		/// </summary>
		public MotoreKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the MotoreKey class.
		/// </summary>
		public MotoreKey(MotoreBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.ID = entity.ID;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the MotoreKey class.
		/// </summary>
		public MotoreKey(System.Int32 _iD)
		{
			#region Init Properties

			this.ID = _iD;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private MotoreBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public MotoreBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the ID property
		private System.Int32 _iD;
		
		/// <summary>
		/// Gets or sets the ID property.
		/// </summary>
		public System.Int32 ID
		{
			get { return _iD; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ID = value;
				
				_iD = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				ID = ( values["ID"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["ID"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("ID", ID);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("ID: {0}{1}",
								ID,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region MotoreColumn Enum
	
	/// <summary>
	/// Enumerate the Motore columns.
	/// </summary>
	[Serializable]
	public enum MotoreColumn : int
	{
		/// <summary>
		/// Descrizione : 
		/// </summary>
		[EnumTextValue("Descrizione")]
		[ColumnEnum("Descrizione", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		Descrizione = 1,
		/// <summary>
		/// ID : 
		/// </summary>
		[EnumTextValue("ID")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		ID = 2,
		/// <summary>
		/// AggregationMotoreID : 
		/// </summary>
		[EnumTextValue("AggregationMotoreID")]
		[ColumnEnum("AggregationMotoreID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		AggregationMotoreID = 3
	}//End enum

	#endregion MotoreColumn Enum

} // end namespace
