
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file RigaFattura.cs instead.
*/

#region using directives

using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

#endregion

namespace GenTest.Entities
{
	///<summary>
	/// An object representation of the 'RigaFattura' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class RigaFatturaBase : EntityBase, GenTest.Entities.IRigaFattura, IEntityId<RigaFatturaKey>, System.IComparable, System.ICloneable, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private RigaFatturaEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private RigaFatturaEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private RigaFatturaEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<RigaFattura> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event RigaFatturaEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event RigaFatturaEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="RigaFatturaBase"/> instance.
		///</summary>
		public RigaFatturaBase()
		{
			this.entityData = new RigaFatturaEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="RigaFatturaBase"/> instance.
		///</summary>
		///<param name="descrizione"></param>
		///<param name="importo"></param>
		///<param name="composedFatturaID"></param>
		///<param name="aggregatedFatturaID"></param>
		///<param name="associatedFatturaID"></param>
		public RigaFatturaBase(System.String descrizione, System.Double importo, System.Int32? composedFatturaID, 
			System.Int32? aggregatedFatturaID, System.Int32? associatedFatturaID)
		{
			this.entityData = new RigaFatturaEntityData();
			this.backupData = null;

			this.Descrizione = descrizione;
			this.Importo = importo;
			this.ComposedFatturaID = composedFatturaID;
			this.AggregatedFatturaID = aggregatedFatturaID;
			this.AssociatedFatturaID = associatedFatturaID;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="RigaFattura"/> instance.
		///</summary>
		///<param name="descrizione"></param>
		///<param name="importo"></param>
		///<param name="composedFatturaID"></param>
		///<param name="aggregatedFatturaID"></param>
		///<param name="associatedFatturaID"></param>
		public static RigaFattura CreateRigaFattura(System.String descrizione, System.Double importo, System.Int32? composedFatturaID, 
			System.Int32? aggregatedFatturaID, System.Int32? associatedFatturaID)
		{
			RigaFattura newRigaFattura = new RigaFattura();
			newRigaFattura.Descrizione = descrizione;
			newRigaFattura.Importo = importo;
			newRigaFattura.ComposedFatturaID = composedFatturaID;
			newRigaFattura.AggregatedFatturaID = aggregatedFatturaID;
			newRigaFattura.AssociatedFatturaID = associatedFatturaID;
			return newRigaFattura;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Descrizione property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public override System.String Descrizione
		{
			get
			{
				return this.entityData.Descrizione; 
			}
			
			set
			{
				if (this.entityData.Descrizione == value)
					return;
					
				OnColumnChanging(RigaFatturaColumn.Descrizione, this.entityData.Descrizione);
				this.entityData.Descrizione = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RigaFatturaColumn.Descrizione, this.entityData.Descrizione);
				OnPropertyChanged("Descrizione");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Importo property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Double Importo
		{
			get
			{
				return this.entityData.Importo; 
			}
			
			set
			{
				if (this.entityData.Importo == value)
					return;
					
				OnColumnChanging(RigaFatturaColumn.Importo, this.entityData.Importo);
				this.entityData.Importo = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RigaFatturaColumn.Importo, this.entityData.Importo);
				OnPropertyChanged("Importo");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public override System.Int32 ID
		{
			get
			{
				return this.entityData.ID; 
			}
			
			set
			{
				if (this.entityData.ID == value)
					return;
					
				OnColumnChanging(RigaFatturaColumn.ID, this.entityData.ID);
				this.entityData.ID = value;
				this.EntityId.ID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RigaFatturaColumn.ID, this.entityData.ID);
				OnPropertyChanged("ID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ComposedFatturaID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsComposedFatturaIDNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? ComposedFatturaID
		{
			get
			{
				return this.entityData.ComposedFatturaID; 
			}
			
			set
			{
				if (this.entityData.ComposedFatturaID == value)
					return;
					
				OnColumnChanging(RigaFatturaColumn.ComposedFatturaID, this.entityData.ComposedFatturaID);
				this.entityData.ComposedFatturaID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RigaFatturaColumn.ComposedFatturaID, this.entityData.ComposedFatturaID);
				OnPropertyChanged("ComposedFatturaID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AggregatedFatturaID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsAggregatedFatturaIDNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? AggregatedFatturaID
		{
			get
			{
				return this.entityData.AggregatedFatturaID; 
			}
			
			set
			{
				if (this.entityData.AggregatedFatturaID == value)
					return;
					
				OnColumnChanging(RigaFatturaColumn.AggregatedFatturaID, this.entityData.AggregatedFatturaID);
				this.entityData.AggregatedFatturaID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RigaFatturaColumn.AggregatedFatturaID, this.entityData.AggregatedFatturaID);
				OnPropertyChanged("AggregatedFatturaID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AssociatedFatturaID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsAssociatedFatturaIDNull() and perform business logic appropriately.
		/// </remarks>
		[DescriptionAttribute(""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? AssociatedFatturaID
		{
			get
			{
				return this.entityData.AssociatedFatturaID; 
			}
			
			set
			{
				if (this.entityData.AssociatedFatturaID == value)
					return;
					
				OnColumnChanging(RigaFatturaColumn.AssociatedFatturaID, this.entityData.AssociatedFatturaID);
				this.entityData.AssociatedFatturaID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(RigaFatturaColumn.AssociatedFatturaID, this.entityData.AssociatedFatturaID);
				OnPropertyChanged("AssociatedFatturaID");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Fattura"/>.
		/// </summary>
		/// <value>The source Fattura for ComposedFatturaID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Fattura ComposedFatturaIDSource
      	{
            get { return entityData.ComposedFatturaIDSource; }
            set { entityData.ComposedFatturaIDSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Fattura"/>.
		/// </summary>
		/// <value>The source Fattura for AggregatedFatturaID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Fattura AggregatedFatturaIDSource
      	{
            get { return entityData.AggregatedFatturaIDSource; }
            set { entityData.AggregatedFatturaIDSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Fattura"/>.
		/// </summary>
		/// <value>The source Fattura for AssociatedFatturaID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Fattura AssociatedFatturaIDSource
      	{
            get { return entityData.AssociatedFatturaIDSource; }
            set { entityData.AssociatedFatturaIDSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Fattura objects
		///	which are related to this object through the relation FK_Aggregated_Fattura_RigaFattura
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Fattura> FatturaCollectionGetByAggregatedRigaFatturaID
		{
			get { return entityData.FatturaCollectionGetByAggregatedRigaFatturaID; }
			set { entityData.FatturaCollectionGetByAggregatedRigaFatturaID = value; }	
		}

		/// <summary>
		///	Holds a Fattura object
		///	which is related to this object through the relation Fattura
		/// </summary>
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Fattura Fattura
		{
			get { return entityData.Fattura; }
			set { entityData.Fattura = value; }	
		}
	
		/// <summary>
		///	Holds a collection of Fattura objects
		///	which are related to this object through the relation FK_Composed_Fattura_RigaFattura
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Fattura> FatturaCollectionGetByComposedRigaFatturaID
		{
			get { return entityData.FatturaCollectionGetByComposedRigaFatturaID; }
			set { entityData.FatturaCollectionGetByComposedRigaFatturaID = value; }	
		}
		#endregion Children Collections
		
		#endregion
		
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule(
				Validation.CommonRules.NotNull,
				new Validation.ValidationRuleArgs("Descrizione", "Descrizione"));
			ValidationRules.AddRule(
				Validation.CommonRules.StringMaxLength, 
				new Validation.CommonRules.MaxLengthRuleArgs("Descrizione", "Descrizione", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "RigaFattura"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Descrizione", "Importo", "ID", "ComposedFatturaID", "AggregatedFatturaID", "AssociatedFatturaID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as RigaFatturaEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (RigaFattura) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<RigaFattura>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as RigaFattura);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed RigaFattura Entity 
		///</summary>
		public virtual RigaFattura Copy()
		{
			//shallow copy entity
			RigaFattura copy = new RigaFattura();
			copy.SuppressEntityEvents = true;
			copy.Descrizione = this.Descrizione;
			copy.Importo = this.Importo;
			copy.ID = this.ID;
			copy.ComposedFatturaID = this.ComposedFatturaID;
			copy.AggregatedFatturaID = this.AggregatedFatturaID;
			copy.AssociatedFatturaID = this.AssociatedFatturaID;
			
			copy.ComposedFatturaIDSource = MakeCopyOf(this.ComposedFatturaIDSource) as Fattura;
			copy.AggregatedFatturaIDSource = MakeCopyOf(this.AggregatedFatturaIDSource) as Fattura;
			copy.AssociatedFatturaIDSource = MakeCopyOf(this.AssociatedFatturaIDSource) as Fattura;
		
			//deep copy nested objects
			copy.FatturaCollectionGetByAggregatedRigaFatturaID = (TList<Fattura>) MakeCopyOf(this.FatturaCollectionGetByAggregatedRigaFatturaID); 
			copy.Fattura = (Fattura) MakeCopyOf(this.Fattura); 
			copy.FatturaCollectionGetByComposedRigaFatturaID = (TList<Fattura>) MakeCopyOf(this.FatturaCollectionGetByComposedRigaFatturaID); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy();
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		///  Returns a Typed RigaFattura Entity which is a deep copy of the current entity.
		///</summary>
		public virtual RigaFattura DeepCopy()
		{
			return EntityHelper.Clone<RigaFattura>(this as RigaFattura);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as RigaFatturaEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as RigaFatturaEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(RigaFatturaColumn column)
		{
			switch(column)
			{
					case RigaFatturaColumn.Descrizione:
					return entityData.Descrizione != _originalData.Descrizione;
					case RigaFatturaColumn.Importo:
					return entityData.Importo != _originalData.Importo;
					case RigaFatturaColumn.ID:
					return entityData.ID != _originalData.ID;
					case RigaFatturaColumn.ComposedFatturaID:
					return entityData.ComposedFatturaID != _originalData.ComposedFatturaID;
					case RigaFatturaColumn.AggregatedFatturaID:
					return entityData.AggregatedFatturaID != _originalData.AggregatedFatturaID;
					case RigaFatturaColumn.AssociatedFatturaID:
					return entityData.AssociatedFatturaID != _originalData.AssociatedFatturaID;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if [has data changed]; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Descrizione != _originalData.Descrizione;
			result = result || entityData.Importo != _originalData.Importo;
			result = result || entityData.ID != _originalData.ID;
			result = result || entityData.ComposedFatturaID != _originalData.ComposedFatturaID;
			result = result || entityData.AggregatedFatturaID != _originalData.AggregatedFatturaID;
			result = result || entityData.AssociatedFatturaID != _originalData.AssociatedFatturaID;
			return result;
}	
		
		#endregion

        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="RigaFatturaBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			if (Object1 is RigaFatturaBase)
				return Equals(this, (RigaFatturaBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="RigaFatturaBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Descrizione.GetHashCode() ^ 
					this.Importo.GetHashCode() ^ 
					this.ID.GetHashCode() ^ 
					((this.ComposedFatturaID == null) ? string.Empty : this.ComposedFatturaID.ToString()).GetHashCode() ^ 
					((this.AggregatedFatturaID == null) ? string.Empty : this.AggregatedFatturaID.ToString()).GetHashCode() ^ 
					((this.AssociatedFatturaID == null) ? string.Empty : this.AssociatedFatturaID.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="RigaFatturaBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(RigaFatturaBase toObject)
		{
			if (toObject == null)
				return false;
			return Equals(this, toObject);
		}
		
		
		///<summary>
		/// Determines whether the specified <see cref="RigaFatturaBase"/> instances are considered equal.
		///</summary>
		///<param name="Object1">The first <see cref="RigaFatturaBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="RigaFatturaBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool Equals(RigaFatturaBase Object1, RigaFatturaBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Descrizione != Object2.Descrizione)
				equal = false;
			if (Object1.Importo != Object2.Importo)
				equal = false;
			if (Object1.ID != Object2.ID)
				equal = false;
			if ( Object1.ComposedFatturaID != null && Object2.ComposedFatturaID != null )
			{
				if (Object1.ComposedFatturaID != Object2.ComposedFatturaID)
					equal = false;
			}
			else if (Object1.ComposedFatturaID == null ^ Object2.ComposedFatturaID == null )
			{
				equal = false;
			}
			if ( Object1.AggregatedFatturaID != null && Object2.AggregatedFatturaID != null )
			{
				if (Object1.AggregatedFatturaID != Object2.AggregatedFatturaID)
					equal = false;
			}
			else if (Object1.AggregatedFatturaID == null ^ Object2.AggregatedFatturaID == null )
			{
				equal = false;
			}
			if ( Object1.AssociatedFatturaID != null && Object2.AssociatedFatturaID != null )
			{
				if (Object1.AssociatedFatturaID != Object2.AssociatedFatturaID)
					equal = false;
			}
			else if (Object1.AssociatedFatturaID == null ^ Object2.AssociatedFatturaID == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((RigaFatturaBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static RigaFatturaComparer GetComparer()
        {
            return new RigaFatturaComparer();
        }
        */

        // Comparer delegates back to RigaFattura
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(RigaFattura rhs, RigaFatturaColumn which)
        {
            switch (which)
            {
            	
            	
            	case RigaFatturaColumn.Descrizione:
            		return this.Descrizione.CompareTo(rhs.Descrizione);
            		
            		                 
            	
            	
            	case RigaFatturaColumn.Importo:
            		return this.Importo.CompareTo(rhs.Importo);
            		
            		                 
            	
            	
            	case RigaFatturaColumn.ID:
            		return this.ID.CompareTo(rhs.ID);
            		
            		                 
            	
            	
            	case RigaFatturaColumn.ComposedFatturaID:
            		return this.ComposedFatturaID.Value.CompareTo(rhs.ComposedFatturaID.Value);
            		
            		                 
            	
            	
            	case RigaFatturaColumn.AggregatedFatturaID:
            		return this.AggregatedFatturaID.Value.CompareTo(rhs.AggregatedFatturaID.Value);
            		
            		                 
            	
            	
            	case RigaFatturaColumn.AssociatedFatturaID:
            		return this.AssociatedFatturaID.Value.CompareTo(rhs.AssociatedFatturaID.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<RigaFatturaKey> Members
		
		// member variable for the EntityId property
		private RigaFatturaKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual RigaFatturaKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new RigaFatturaKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("RigaFattura")
					.Append("|").Append( this.ID.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- Descrizione: {0}{6}- Importo: {1}{6}- ID: {2}{6}- ComposedFatturaID: {3}{6}- AggregatedFatturaID: {4}{6}- AssociatedFatturaID: {5}{6}", 
				this.Descrizione,
				this.Importo,
				this.ID,
				(this.ComposedFatturaID == null) ? string.Empty : this.ComposedFatturaID.ToString(),
				(this.AggregatedFatturaID == null) ? string.Empty : this.AggregatedFatturaID.ToString(),
				(this.AssociatedFatturaID == null) ? string.Empty : this.AssociatedFatturaID.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'RigaFattura' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class RigaFatturaEntityData : ICloneable
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// ID : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "RigaFattura"</remarks>
			public System.Int32 ID;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Descrizione : 
		/// </summary>
		public System.String		  Descrizione = string.Empty;
		
		/// <summary>
		/// Importo : 
		/// </summary>
		public System.Double		  Importo = 0.0f;
		
		/// <summary>
		/// ComposedFatturaID : 
		/// </summary>
		public System.Int32?		  ComposedFatturaID = null;
		
		/// <summary>
		/// AggregatedFatturaID : 
		/// </summary>
		public System.Int32?		  AggregatedFatturaID = null;
		
		/// <summary>
		/// AssociatedFatturaID : 
		/// </summary>
		public System.Int32?		  AssociatedFatturaID = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Fattura _composedFatturaIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Fattura"/>.
		/// </summary>
		/// <value>The source Fattura for ComposedFatturaID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Fattura ComposedFatturaIDSource
      	{
            get { return this._composedFatturaIDSource; }
            set { this._composedFatturaIDSource = value; }
      	}
		private Fattura _aggregatedFatturaIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Fattura"/>.
		/// </summary>
		/// <value>The source Fattura for AggregatedFatturaID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Fattura AggregatedFatturaIDSource
      	{
            get { return this._aggregatedFatturaIDSource; }
            set { this._aggregatedFatturaIDSource = value; }
      	}
		private Fattura _associatedFatturaIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Fattura"/>.
		/// </summary>
		/// <value>The source Fattura for AssociatedFatturaID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Fattura AssociatedFatturaIDSource
      	{
            get { return this._associatedFatturaIDSource; }
            set { this._associatedFatturaIDSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region FatturaCollectionGetByAggregatedRigaFatturaID
		
		private TList<Fattura> fatturaAggregatedRigaFatturaIDGetByAggregatedRigaFatturaID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation fatturaAggregatedRigaFatturaIDGetByAggregatedRigaFatturaID
		/// </summary>	
		public TList<Fattura> FatturaCollectionGetByAggregatedRigaFatturaID
		{
			get
			{
				if (fatturaAggregatedRigaFatturaIDGetByAggregatedRigaFatturaID == null)
				{
				fatturaAggregatedRigaFatturaIDGetByAggregatedRigaFatturaID = new TList<Fattura>();
				}
	
				return fatturaAggregatedRigaFatturaIDGetByAggregatedRigaFatturaID;
			}
			set { fatturaAggregatedRigaFatturaIDGetByAggregatedRigaFatturaID = value; }
		}
		
		#endregion

		#region Fattura
		
		private Fattura fatturaAssociatedRigaFatturaID;
		
		/// <summary>
		///	Holds a  Fattura entity object
		///	which is related to this object through the relation fatturaAssociatedRigaFatturaID
		/// </summary>
		public Fattura Fattura
		{
			get {		return fatturaAssociatedRigaFatturaID;		}
			set { 	fatturaAssociatedRigaFatturaID = value; 	}
		}
		
		#endregion 

		#region FatturaCollectionGetByComposedRigaFatturaID
		
		private TList<Fattura> fatturaAggregatedRigaFatturaIDGetByComposedRigaFatturaID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation fatturaAggregatedRigaFatturaIDGetByComposedRigaFatturaID
		/// </summary>	
		public TList<Fattura> FatturaCollectionGetByComposedRigaFatturaID
		{
			get
			{
				if (fatturaAggregatedRigaFatturaIDGetByComposedRigaFatturaID == null)
				{
				fatturaAggregatedRigaFatturaIDGetByComposedRigaFatturaID = new TList<Fattura>();
				}
	
				return fatturaAggregatedRigaFatturaIDGetByComposedRigaFatturaID;
			}
			set { fatturaAggregatedRigaFatturaIDGetByComposedRigaFatturaID = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			RigaFatturaEntityData _tmp = new RigaFatturaEntityData();
						
			_tmp.ID = this.ID;
			
			_tmp.Descrizione = this.Descrizione;
			_tmp.Importo = this.Importo;
			_tmp.ComposedFatturaID = this.ComposedFatturaID;
			_tmp.AggregatedFatturaID = this.AggregatedFatturaID;
			_tmp.AssociatedFatturaID = this.AssociatedFatturaID;
			
			#region Source Parent Composite Entities
			if (this.ComposedFatturaIDSource != null)
				_tmp.ComposedFatturaIDSource = MakeCopyOf(this.ComposedFatturaIDSource) as Fattura;
			if (this.AggregatedFatturaIDSource != null)
				_tmp.AggregatedFatturaIDSource = MakeCopyOf(this.AggregatedFatturaIDSource) as Fattura;
			if (this.AssociatedFatturaIDSource != null)
				_tmp.AssociatedFatturaIDSource = MakeCopyOf(this.AssociatedFatturaIDSource) as Fattura;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this.fatturaAggregatedRigaFatturaIDGetByAggregatedRigaFatturaID != null)
				_tmp.FatturaCollectionGetByAggregatedRigaFatturaID = (TList<Fattura>) MakeCopyOf(this.FatturaCollectionGetByAggregatedRigaFatturaID); 
			if (this.fatturaAssociatedRigaFatturaID != null)
				_tmp.Fattura = (Fattura) MakeCopyOf(this.Fattura); 
			if (this.fatturaAggregatedRigaFatturaIDGetByComposedRigaFatturaID != null)
				_tmp.FatturaCollectionGetByComposedRigaFatturaID = (TList<Fattura>) MakeCopyOf(this.FatturaCollectionGetByComposedRigaFatturaID); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct



		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RigaFatturaColumn"/> which has raised the event.</param>
		public void OnColumnChanging(RigaFatturaColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RigaFatturaColumn"/> which has raised the event.</param>
		public void OnColumnChanged(RigaFatturaColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RigaFatturaColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanging(RigaFatturaColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				RigaFatturaEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new RigaFatturaEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="RigaFatturaColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public void OnColumnChanged(RigaFatturaColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				RigaFatturaEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new RigaFatturaEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region RigaFatturaEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="RigaFattura"/> object.
	/// </remarks>
	public class RigaFatturaEventArgs : System.EventArgs
	{
		private RigaFatturaColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the RigaFatturaEventArgs class.
		///</summary>
		public RigaFatturaEventArgs(RigaFatturaColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the RigaFatturaEventArgs class.
		///</summary>
		public RigaFatturaEventArgs(RigaFatturaColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The RigaFatturaColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="RigaFatturaColumn" />
		public RigaFatturaColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all RigaFattura related events.
	///</summary>
	public delegate void RigaFatturaEventHandler(object sender, RigaFatturaEventArgs e);
	
	#region RigaFatturaComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class RigaFatturaComparer : System.Collections.Generic.IComparer<RigaFattura>
	{
		RigaFatturaColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:RigaFatturaComparer"/> class.
        /// </summary>
		public RigaFatturaComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:RigaFatturaComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public RigaFatturaComparer(RigaFatturaColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="RigaFattura"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="RigaFattura"/> to compare.</param>
        /// <param name="b">The second <c>RigaFattura</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(RigaFattura a, RigaFattura b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(RigaFattura entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(RigaFattura a, RigaFattura b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public RigaFatturaColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region RigaFatturaKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="RigaFattura"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class RigaFatturaKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the RigaFatturaKey class.
		/// </summary>
		public RigaFatturaKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the RigaFatturaKey class.
		/// </summary>
		public RigaFatturaKey(RigaFatturaBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.ID = entity.ID;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the RigaFatturaKey class.
		/// </summary>
		public RigaFatturaKey(System.Int32 iD)
		{
			#region Init Properties

			this.ID = iD;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private RigaFatturaBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public RigaFatturaBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the ID property
		private System.Int32 _iD;
		
		/// <summary>
		/// Gets or sets the ID property.
		/// </summary>
		public System.Int32 ID
		{
			get { return _iD; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ID = value;
				
				_iD = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				ID = ( values["ID"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["ID"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("ID", ID);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("ID: {0}{1}",
								ID,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region RigaFatturaColumn Enum
	
	/// <summary>
	/// Enumerate the RigaFattura columns.
	/// </summary>
	[Serializable]
	public enum RigaFatturaColumn : int
	{
		/// <summary>
		/// Descrizione : 
		/// </summary>
		[EnumTextValue("Descrizione")]
		[ColumnEnum("Descrizione", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		Descrizione = 1,
		/// <summary>
		/// Importo : 
		/// </summary>
		[EnumTextValue("Importo")]
		[ColumnEnum("Importo", typeof(System.Double), System.Data.DbType.Double, false, false, false)]
		Importo = 2,
		/// <summary>
		/// ID : 
		/// </summary>
		[EnumTextValue("ID")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		ID = 3,
		/// <summary>
		/// ComposedFatturaID : 
		/// </summary>
		[EnumTextValue("ComposedFatturaID")]
		[ColumnEnum("ComposedFatturaID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ComposedFatturaID = 4,
		/// <summary>
		/// AggregatedFatturaID : 
		/// </summary>
		[EnumTextValue("AggregatedFatturaID")]
		[ColumnEnum("AggregatedFatturaID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		AggregatedFatturaID = 5,
		/// <summary>
		/// AssociatedFatturaID : 
		/// </summary>
		[EnumTextValue("AssociatedFatturaID")]
		[ColumnEnum("AssociatedFatturaID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		AssociatedFatturaID = 6
	}//End enum

	#endregion RigaFatturaColumn Enum

} // end namespace
