
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Specchietto.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using GenTest.Entities.Validation;
#endregion

namespace GenTest.Entities
{
	///<summary>
	/// An object representation of the 'Specchietto' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class SpecchiettoBase : EntityBase, ISpecchietto, IEntityId<SpecchiettoKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private SpecchiettoEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private SpecchiettoEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private SpecchiettoEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Specchietto> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event SpecchiettoEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event SpecchiettoEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="SpecchiettoBase"/> instance.
		///</summary>
		public SpecchiettoBase()
		{
			this.entityData = new SpecchiettoEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="SpecchiettoBase"/> instance.
		///</summary>
		///<param name="_larghezza"></param>
		///<param name="_aggregationMacchinaID"></param>
		///<param name="_sgutAssociationSpecchiettoID"></param>
		///<param name="_associationSpecchiettoID"></param>
		public SpecchiettoBase(System.Double _larghezza, System.Int32? _aggregationMacchinaID, 
			System.Int32? _sgutAssociationSpecchiettoID, System.Int32? _associationSpecchiettoID)
		{
			this.entityData = new SpecchiettoEntityData();
			this.backupData = null;

			this.Larghezza = _larghezza;
			this.AggregationMacchinaID = _aggregationMacchinaID;
			this.SgutAssociationSpecchiettoID = _sgutAssociationSpecchiettoID;
			this.AssociationSpecchiettoID = _associationSpecchiettoID;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Specchietto"/> instance.
		///</summary>
		///<param name="_larghezza"></param>
		///<param name="_aggregationMacchinaID"></param>
		///<param name="_sgutAssociationSpecchiettoID"></param>
		///<param name="_associationSpecchiettoID"></param>
		public static Specchietto CreateSpecchietto(System.Double _larghezza, System.Int32? _aggregationMacchinaID, 
			System.Int32? _sgutAssociationSpecchiettoID, System.Int32? _associationSpecchiettoID)
		{
			Specchietto newSpecchietto = new Specchietto();
			newSpecchietto.Larghezza = _larghezza;
			newSpecchietto.AggregationMacchinaID = _aggregationMacchinaID;
			newSpecchietto.SgutAssociationSpecchiettoID = _sgutAssociationSpecchiettoID;
			newSpecchietto.AssociationSpecchiettoID = _associationSpecchiettoID;
			return newSpecchietto;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Larghezza property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Double Larghezza
		{
			get
			{
				return this.entityData.Larghezza; 
			}
			
			set
			{
				if (this.entityData.Larghezza == value)
					return;
					
				OnColumnChanging(SpecchiettoColumn.Larghezza, this.entityData.Larghezza);
				this.entityData.Larghezza = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SpecchiettoColumn.Larghezza, this.entityData.Larghezza);
				OnPropertyChanged("Larghezza");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public override System.Int32 ID
		{
			get
			{
				return this.entityData.ID; 
			}
			
			set
			{
				if (this.entityData.ID == value)
					return;
					
				OnColumnChanging(SpecchiettoColumn.ID, this.entityData.ID);
				this.entityData.ID = value;
				this.EntityId.ID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SpecchiettoColumn.ID, this.entityData.ID);
				OnPropertyChanged("ID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AggregationMacchinaID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsAggregationMacchinaIDNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? AggregationMacchinaID
		{
			get
			{
				return this.entityData.AggregationMacchinaID; 
			}
			
			set
			{
				if (this.entityData.AggregationMacchinaID == value)
					return;
					
				OnColumnChanging(SpecchiettoColumn.AggregationMacchinaID, this.entityData.AggregationMacchinaID);
				this.entityData.AggregationMacchinaID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SpecchiettoColumn.AggregationMacchinaID, this.entityData.AggregationMacchinaID);
				OnPropertyChanged("AggregationMacchinaID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SgutAssociationSpecchiettoID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsSgutAssociationSpecchiettoIDNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? SgutAssociationSpecchiettoID
		{
			get
			{
				return this.entityData.SgutAssociationSpecchiettoID; 
			}
			
			set
			{
				if (this.entityData.SgutAssociationSpecchiettoID == value)
					return;
					
				OnColumnChanging(SpecchiettoColumn.SgutAssociationSpecchiettoID, this.entityData.SgutAssociationSpecchiettoID);
				this.entityData.SgutAssociationSpecchiettoID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SpecchiettoColumn.SgutAssociationSpecchiettoID, this.entityData.SgutAssociationSpecchiettoID);
				OnPropertyChanged("SgutAssociationSpecchiettoID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AssociationSpecchiettoID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsAssociationSpecchiettoIDNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? AssociationSpecchiettoID
		{
			get
			{
				return this.entityData.AssociationSpecchiettoID; 
			}
			
			set
			{
				if (this.entityData.AssociationSpecchiettoID == value)
					return;
					
				OnColumnChanging(SpecchiettoColumn.AssociationSpecchiettoID, this.entityData.AssociationSpecchiettoID);
				this.entityData.AssociationSpecchiettoID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(SpecchiettoColumn.AssociationSpecchiettoID, this.entityData.AssociationSpecchiettoID);
				OnPropertyChanged("AssociationSpecchiettoID");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Macchina"/>.
		/// </summary>
		/// <value>The source Macchina for AggregationMacchinaID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Macchina AggregationMacchinaIDSource
      	{
            get { return entityData.AggregationMacchinaIDSource; }
            set { entityData.AggregationMacchinaIDSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Specchietto"/>.
		/// </summary>
		/// <value>The source Specchietto for SgutAssociationSpecchiettoID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Specchietto SgutAssociationSpecchiettoIDSource
      	{
            get { return entityData.SgutAssociationSpecchiettoIDSource; }
            set { entityData.SgutAssociationSpecchiettoIDSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Specchietto"/>.
		/// </summary>
		/// <value>The source Specchietto for AssociationSpecchiettoID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Specchietto AssociationSpecchiettoIDSource
      	{
            get { return entityData.AssociationSpecchiettoIDSource; }
            set { entityData.AssociationSpecchiettoIDSource = value; }
      	}
		#endregion
		
		#region Children Collections

		/// <summary>
		///	Holds a SpecchiettoGetBySgutAssociationSpecchiettoID object
		///	which is related to this object through the relation Specchietto
		/// </summary>
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual SpecchiettoGetBySgutAssociationSpecchiettoID SpecchiettoGetBySgutAssociationSpecchiettoID
		{
			get { return entityData.SpecchiettoGetBySgutAssociationSpecchiettoID; }
			set { entityData.SpecchiettoGetBySgutAssociationSpecchiettoID = value; }	
		}

		/// <summary>
		///	Holds a SpecchiettoGetByAssociationSpecchiettoID object
		///	which is related to this object through the relation Specchietto
		/// </summary>
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual SpecchiettoGetByAssociationSpecchiettoID SpecchiettoGetByAssociationSpecchiettoID
		{
			get { return entityData.SpecchiettoGetByAssociationSpecchiettoID; }
			set { entityData.SpecchiettoGetByAssociationSpecchiettoID = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Specchietto"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Larghezza", "ID", "AggregationMacchinaID", "SgutAssociationSpecchiettoID", "AssociationSpecchiettoID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as SpecchiettoEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Specchietto) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Specchietto>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Specchietto);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Specchietto Entity 
		///</summary>
		protected virtual Specchietto Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Specchietto copy = new Specchietto();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Larghezza = this.Larghezza;
				copy.ID = this.ID;
				copy.AggregationMacchinaID = this.AggregationMacchinaID;
				copy.SgutAssociationSpecchiettoID = this.SgutAssociationSpecchiettoID;
				copy.AssociationSpecchiettoID = this.AssociationSpecchiettoID;
			
			if (this.AggregationMacchinaIDSource != null && existingCopies.Contains(this.AggregationMacchinaIDSource))
				copy.AggregationMacchinaIDSource = existingCopies[this.AggregationMacchinaIDSource] as Macchina;
			else
				copy.AggregationMacchinaIDSource = MakeCopyOf(this.AggregationMacchinaIDSource, existingCopies) as Macchina;
			if (this.SgutAssociationSpecchiettoIDSource != null && existingCopies.Contains(this.SgutAssociationSpecchiettoIDSource))
				copy.SgutAssociationSpecchiettoIDSource = existingCopies[this.SgutAssociationSpecchiettoIDSource] as Specchietto;
			else
				copy.SgutAssociationSpecchiettoIDSource = MakeCopyOf(this.SgutAssociationSpecchiettoIDSource, existingCopies) as Specchietto;
			if (this.AssociationSpecchiettoIDSource != null && existingCopies.Contains(this.AssociationSpecchiettoIDSource))
				copy.AssociationSpecchiettoIDSource = existingCopies[this.AssociationSpecchiettoIDSource] as Specchietto;
			else
				copy.AssociationSpecchiettoIDSource = MakeCopyOf(this.AssociationSpecchiettoIDSource, existingCopies) as Specchietto;
		
			//deep copy nested objects
			copy.SpecchiettoGetBySgutAssociationSpecchiettoID = (Specchietto) MakeCopyOf(this.SpecchiettoGetBySgutAssociationSpecchiettoID, existingCopies); 
			copy.SpecchiettoGetByAssociationSpecchiettoID = (Specchietto) MakeCopyOf(this.SpecchiettoGetByAssociationSpecchiettoID, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Specchietto Entity 
		///</summary>
		public virtual Specchietto Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Specchietto Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Specchietto DeepCopy()
		{
			return EntityHelper.Clone<Specchietto>(this as Specchietto);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as SpecchiettoEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as SpecchiettoEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(SpecchiettoColumn column)
		{
			switch(column)
			{
					case SpecchiettoColumn.Larghezza:
					return entityData.Larghezza != _originalData.Larghezza;
					case SpecchiettoColumn.ID:
					return entityData.ID != _originalData.ID;
					case SpecchiettoColumn.AggregationMacchinaID:
					return entityData.AggregationMacchinaID != _originalData.AggregationMacchinaID;
					case SpecchiettoColumn.SgutAssociationSpecchiettoID:
					return entityData.SgutAssociationSpecchiettoID != _originalData.SgutAssociationSpecchiettoID;
					case SpecchiettoColumn.AssociationSpecchiettoID:
					return entityData.AssociationSpecchiettoID != _originalData.AssociationSpecchiettoID;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Larghezza != _originalData.Larghezza;
			result = result || entityData.ID != _originalData.ID;
			result = result || entityData.AggregationMacchinaID != _originalData.AggregationMacchinaID;
			result = result || entityData.SgutAssociationSpecchiettoID != _originalData.SgutAssociationSpecchiettoID;
			result = result || entityData.AssociationSpecchiettoID != _originalData.AssociationSpecchiettoID;
			return result;
		}	
		
		///<summary>
		///  Returns a Specchietto Entity with the original data.
		///</summary>
		public Specchietto GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateSpecchietto(
				_originalData.Larghezza,
				_originalData.AggregationMacchinaID,
				_originalData.SgutAssociationSpecchiettoID,
				_originalData.AssociationSpecchiettoID
				);
				
			return (Specchietto)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="SpecchiettoBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is SpecchiettoBase)
				return ValueEquals(this, (SpecchiettoBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="SpecchiettoBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Larghezza.GetHashCode() ^ 
					this.ID.GetHashCode() ^ 
					((this.AggregationMacchinaID == null) ? string.Empty : this.AggregationMacchinaID.ToString()).GetHashCode() ^ 
					((this.SgutAssociationSpecchiettoID == null) ? string.Empty : this.SgutAssociationSpecchiettoID.ToString()).GetHashCode() ^ 
					((this.AssociationSpecchiettoID == null) ? string.Empty : this.AssociationSpecchiettoID.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="SpecchiettoBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(SpecchiettoBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="SpecchiettoBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="SpecchiettoBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="SpecchiettoBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(SpecchiettoBase Object1, SpecchiettoBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Larghezza != Object2.Larghezza)
				equal = false;
			if (Object1.ID != Object2.ID)
				equal = false;
			if ( Object1.AggregationMacchinaID != null && Object2.AggregationMacchinaID != null )
			{
				if (Object1.AggregationMacchinaID != Object2.AggregationMacchinaID)
					equal = false;
			}
			else if (Object1.AggregationMacchinaID == null ^ Object2.AggregationMacchinaID == null )
			{
				equal = false;
			}
			if ( Object1.SgutAssociationSpecchiettoID != null && Object2.SgutAssociationSpecchiettoID != null )
			{
				if (Object1.SgutAssociationSpecchiettoID != Object2.SgutAssociationSpecchiettoID)
					equal = false;
			}
			else if (Object1.SgutAssociationSpecchiettoID == null ^ Object2.SgutAssociationSpecchiettoID == null )
			{
				equal = false;
			}
			if ( Object1.AssociationSpecchiettoID != null && Object2.AssociationSpecchiettoID != null )
			{
				if (Object1.AssociationSpecchiettoID != Object2.AssociationSpecchiettoID)
					equal = false;
			}
			else if (Object1.AssociationSpecchiettoID == null ^ Object2.AssociationSpecchiettoID == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((SpecchiettoBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static SpecchiettoComparer GetComparer()
        {
            return new SpecchiettoComparer();
        }
        */

        // Comparer delegates back to Specchietto
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Specchietto rhs, SpecchiettoColumn which)
        {
            switch (which)
            {
            	
            	
            	case SpecchiettoColumn.Larghezza:
            		return this.Larghezza.CompareTo(rhs.Larghezza);
            		
            		                 
            	
            	
            	case SpecchiettoColumn.ID:
            		return this.ID.CompareTo(rhs.ID);
            		
            		                 
            	
            	
            	case SpecchiettoColumn.AggregationMacchinaID:
            		return this.AggregationMacchinaID.Value.CompareTo(rhs.AggregationMacchinaID.Value);
            		
            		                 
            	
            	
            	case SpecchiettoColumn.SgutAssociationSpecchiettoID:
            		return this.SgutAssociationSpecchiettoID.Value.CompareTo(rhs.SgutAssociationSpecchiettoID.Value);
            		
            		                 
            	
            	
            	case SpecchiettoColumn.AssociationSpecchiettoID:
            		return this.AssociationSpecchiettoID.Value.CompareTo(rhs.AssociationSpecchiettoID.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<SpecchiettoKey> Members
		
		// member variable for the EntityId property
		private SpecchiettoKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual SpecchiettoKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new SpecchiettoKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Specchietto")
					.Append("|").Append( this.ID.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- Larghezza: {0}{5}- ID: {1}{5}- AggregationMacchinaID: {2}{5}- SgutAssociationSpecchiettoID: {3}{5}- AssociationSpecchiettoID: {4}{5}", 
				this.Larghezza,
				this.ID,
				(this.AggregationMacchinaID == null) ? string.Empty : this.AggregationMacchinaID.ToString(),
				(this.SgutAssociationSpecchiettoID == null) ? string.Empty : this.SgutAssociationSpecchiettoID.ToString(),
				(this.AssociationSpecchiettoID == null) ? string.Empty : this.AssociationSpecchiettoID.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Specchietto' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class SpecchiettoEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// ID : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "Specchietto"</remarks>
			public System.Int32 ID;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Larghezza : 
		/// </summary>
		public System.Double		  Larghezza = 0.0f;
		
		/// <summary>
		/// AggregationMacchinaID : 
		/// </summary>
		public System.Int32?		  AggregationMacchinaID = null;
		
		/// <summary>
		/// SgutAssociationSpecchiettoID : 
		/// </summary>
		public System.Int32?		  SgutAssociationSpecchiettoID = null;
		
		/// <summary>
		/// AssociationSpecchiettoID : 
		/// </summary>
		public System.Int32?		  AssociationSpecchiettoID = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Macchina _aggregationMacchinaIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Macchina"/>.
		/// </summary>
		/// <value>The source Macchina for AggregationMacchinaID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Macchina AggregationMacchinaIDSource
      	{
            get { return this._aggregationMacchinaIDSource; }
            set { this._aggregationMacchinaIDSource = value; }
      	}
		private Specchietto _sgutAssociationSpecchiettoIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Specchietto"/>.
		/// </summary>
		/// <value>The source Specchietto for SgutAssociationSpecchiettoID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Specchietto SgutAssociationSpecchiettoIDSource
      	{
            get { return this._sgutAssociationSpecchiettoIDSource; }
            set { this._sgutAssociationSpecchiettoIDSource = value; }
      	}
		private Specchietto _associationSpecchiettoIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Specchietto"/>.
		/// </summary>
		/// <value>The source Specchietto for AssociationSpecchiettoID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Specchietto AssociationSpecchiettoIDSource
      	{
            get { return this._associationSpecchiettoIDSource; }
            set { this._associationSpecchiettoIDSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region SpecchiettoGetBySgutAssociationSpecchiettoID
		
		private Specchietto _specchiettoAssociationSpecchiettoIDGetBySgutAssociationSpecchiettoID;
		
		/// <summary>
		///	Holds a  Specchietto entity object
		///	which is related to this object through the relation _specchiettoAssociationSpecchiettoIDGetBySgutAssociationSpecchiettoID
		/// </summary>
		public Specchietto SpecchiettoGetBySgutAssociationSpecchiettoID
		{
			get {		return _specchiettoAssociationSpecchiettoIDGetBySgutAssociationSpecchiettoID;		}
			set { 	_specchiettoAssociationSpecchiettoIDGetBySgutAssociationSpecchiettoID = value; 	}
		}
		
		#endregion 

		#region SpecchiettoGetByAssociationSpecchiettoID
		
		private Specchietto _specchiettoAssociationSpecchiettoIDGetByAssociationSpecchiettoID;
		
		/// <summary>
		///	Holds a  Specchietto entity object
		///	which is related to this object through the relation _specchiettoAssociationSpecchiettoIDGetByAssociationSpecchiettoID
		/// </summary>
		public Specchietto SpecchiettoGetByAssociationSpecchiettoID
		{
			get {		return _specchiettoAssociationSpecchiettoIDGetByAssociationSpecchiettoID;		}
			set { 	_specchiettoAssociationSpecchiettoIDGetByAssociationSpecchiettoID = value; 	}
		}
		
		#endregion 

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			SpecchiettoEntityData _tmp = new SpecchiettoEntityData();
						
			_tmp.ID = this.ID;
			
			_tmp.Larghezza = this.Larghezza;
			_tmp.AggregationMacchinaID = this.AggregationMacchinaID;
			_tmp.SgutAssociationSpecchiettoID = this.SgutAssociationSpecchiettoID;
			_tmp.AssociationSpecchiettoID = this.AssociationSpecchiettoID;
			
			#region Source Parent Composite Entities
			if (this.AggregationMacchinaIDSource != null)
				_tmp.AggregationMacchinaIDSource = MakeCopyOf(this.AggregationMacchinaIDSource) as Macchina;
			if (this.SgutAssociationSpecchiettoIDSource != null)
				_tmp.SgutAssociationSpecchiettoIDSource = MakeCopyOf(this.SgutAssociationSpecchiettoIDSource) as Specchietto;
			if (this.AssociationSpecchiettoIDSource != null)
				_tmp.AssociationSpecchiettoIDSource = MakeCopyOf(this.AssociationSpecchiettoIDSource) as Specchietto;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._specchiettoAssociationSpecchiettoIDGetBySgutAssociationSpecchiettoID != null)
				_tmp.SpecchiettoGetBySgutAssociationSpecchiettoID = (Specchietto) MakeCopyOf(this.SpecchiettoGetBySgutAssociationSpecchiettoID); 
			if (this._specchiettoAssociationSpecchiettoIDGetByAssociationSpecchiettoID != null)
				_tmp.SpecchiettoGetByAssociationSpecchiettoID = (Specchietto) MakeCopyOf(this.SpecchiettoGetByAssociationSpecchiettoID); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			SpecchiettoEntityData _tmp = new SpecchiettoEntityData();
						
			_tmp.ID = this.ID;
			
			_tmp.Larghezza = this.Larghezza;
			_tmp.AggregationMacchinaID = this.AggregationMacchinaID;
			_tmp.SgutAssociationSpecchiettoID = this.SgutAssociationSpecchiettoID;
			_tmp.AssociationSpecchiettoID = this.AssociationSpecchiettoID;
			
			#region Source Parent Composite Entities
			if (this.AggregationMacchinaIDSource != null && existingCopies.Contains(this.AggregationMacchinaIDSource))
				_tmp.AggregationMacchinaIDSource = existingCopies[this.AggregationMacchinaIDSource] as Macchina;
			else
				_tmp.AggregationMacchinaIDSource = MakeCopyOf(this.AggregationMacchinaIDSource, existingCopies) as Macchina;
			if (this.SgutAssociationSpecchiettoIDSource != null && existingCopies.Contains(this.SgutAssociationSpecchiettoIDSource))
				_tmp.SgutAssociationSpecchiettoIDSource = existingCopies[this.SgutAssociationSpecchiettoIDSource] as Specchietto;
			else
				_tmp.SgutAssociationSpecchiettoIDSource = MakeCopyOf(this.SgutAssociationSpecchiettoIDSource, existingCopies) as Specchietto;
			if (this.AssociationSpecchiettoIDSource != null && existingCopies.Contains(this.AssociationSpecchiettoIDSource))
				_tmp.AssociationSpecchiettoIDSource = existingCopies[this.AssociationSpecchiettoIDSource] as Specchietto;
			else
				_tmp.AssociationSpecchiettoIDSource = MakeCopyOf(this.AssociationSpecchiettoIDSource, existingCopies) as Specchietto;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.SpecchiettoGetBySgutAssociationSpecchiettoID = (Specchietto) MakeCopyOf(this.SpecchiettoGetBySgutAssociationSpecchiettoID, existingCopies); 
			_tmp.SpecchiettoGetByAssociationSpecchiettoID = (Specchietto) MakeCopyOf(this.SpecchiettoGetByAssociationSpecchiettoID, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SpecchiettoColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(SpecchiettoColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SpecchiettoColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(SpecchiettoColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SpecchiettoColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(SpecchiettoColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				SpecchiettoEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new SpecchiettoEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="SpecchiettoColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(SpecchiettoColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				SpecchiettoEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new SpecchiettoEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region SpecchiettoEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Specchietto"/> object.
	/// </remarks>
	public class SpecchiettoEventArgs : System.EventArgs
	{
		private SpecchiettoColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the SpecchiettoEventArgs class.
		///</summary>
		public SpecchiettoEventArgs(SpecchiettoColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the SpecchiettoEventArgs class.
		///</summary>
		public SpecchiettoEventArgs(SpecchiettoColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The SpecchiettoColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="SpecchiettoColumn" />
		public SpecchiettoColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Specchietto related events.
	///</summary>
	public delegate void SpecchiettoEventHandler(object sender, SpecchiettoEventArgs e);
	
	#region SpecchiettoComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class SpecchiettoComparer : System.Collections.Generic.IComparer<Specchietto>
	{
		SpecchiettoColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:SpecchiettoComparer"/> class.
        /// </summary>
		public SpecchiettoComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:SpecchiettoComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public SpecchiettoComparer(SpecchiettoColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Specchietto"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Specchietto"/> to compare.</param>
        /// <param name="b">The second <c>Specchietto</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Specchietto a, Specchietto b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Specchietto entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Specchietto a, Specchietto b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public SpecchiettoColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region SpecchiettoKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Specchietto"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class SpecchiettoKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the SpecchiettoKey class.
		/// </summary>
		public SpecchiettoKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the SpecchiettoKey class.
		/// </summary>
		public SpecchiettoKey(SpecchiettoBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.ID = entity.ID;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the SpecchiettoKey class.
		/// </summary>
		public SpecchiettoKey(System.Int32 _iD)
		{
			#region Init Properties

			this.ID = _iD;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private SpecchiettoBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public SpecchiettoBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the ID property
		private System.Int32 _iD;
		
		/// <summary>
		/// Gets or sets the ID property.
		/// </summary>
		public System.Int32 ID
		{
			get { return _iD; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ID = value;
				
				_iD = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				ID = ( values["ID"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["ID"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("ID", ID);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("ID: {0}{1}",
								ID,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region SpecchiettoColumn Enum
	
	/// <summary>
	/// Enumerate the Specchietto columns.
	/// </summary>
	[Serializable]
	public enum SpecchiettoColumn : int
	{
		/// <summary>
		/// Larghezza : 
		/// </summary>
		[EnumTextValue("Larghezza")]
		[ColumnEnum("Larghezza", typeof(System.Double), System.Data.DbType.Double, false, false, false)]
		Larghezza = 1,
		/// <summary>
		/// ID : 
		/// </summary>
		[EnumTextValue("ID")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		ID = 2,
		/// <summary>
		/// AggregationMacchinaID : 
		/// </summary>
		[EnumTextValue("AggregationMacchinaID")]
		[ColumnEnum("AggregationMacchinaID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		AggregationMacchinaID = 3,
		/// <summary>
		/// SgutAssociationSpecchiettoID : 
		/// </summary>
		[EnumTextValue("SgutAssociationSpecchiettoID")]
		[ColumnEnum("SgutAssociationSpecchiettoID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		SgutAssociationSpecchiettoID = 4,
		/// <summary>
		/// AssociationSpecchiettoID : 
		/// </summary>
		[EnumTextValue("AssociationSpecchiettoID")]
		[ColumnEnum("AssociationSpecchiettoID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		AssociationSpecchiettoID = 5
	}//End enum

	#endregion SpecchiettoColumn Enum

} // end namespace
