using System;
using System.ComponentModel;

namespace GenTest.Entities
{
	/// <summary>
	///		The data structure representation of the 'Fattura' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IFattura 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Fattura"</remarks>
		System.Int32 ID { get; set; }
				
		
		
		/// <summary>
		/// Intestatario : 
		/// </summary>
		System.String  Intestatario  { get; set; }
		
		/// <summary>
		/// Descrizione : 
		/// </summary>
		System.String  Descrizione  { get; set; }
		
		/// <summary>
		/// Data : 
		/// </summary>
		System.String  Data  { get; set; }
		
		/// <summary>
		/// Numero : 
		/// </summary>
		System.Int32  Numero  { get; set; }
		
		/// <summary>
		/// ComposedRigaFatturaID : 
		/// </summary>
		System.Int32?  ComposedRigaFatturaID  { get; set; }
		
		/// <summary>
		/// AggregatedRigaFatturaID : 
		/// </summary>
		System.Int32?  AggregatedRigaFatturaID  { get; set; }
		
		/// <summary>
		/// AssociatedRigaFatturaID : 
		/// </summary>
		System.Int32?  AssociatedRigaFatturaID  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties
	

		/// <summary>
		///	Holds a  RigaFattura entity object
		///	which is related to this object through the relation rigaFatturaAssociatedFatturaID
		/// </summary>
		RigaFattura RigaFattura { get; set; }


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation rigaFatturaAggregatedFatturaIDGetByComposedFatturaID
		/// </summary>	
		TList<RigaFattura> RigaFatturaCollectionGetByComposedFatturaID {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation rigaFatturaAggregatedFatturaIDGetByAggregatedFatturaID
		/// </summary>	
		TList<RigaFattura> RigaFatturaCollectionGetByAggregatedFatturaID {  get;  set;}	

		#endregion Data Properties

	}
}


