using System;
using System.ComponentModel;

namespace GenTest.Entities
{
	/// <summary>
	///		The data structure representation of the 'Macchina' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IMacchina 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Macchina"</remarks>
		System.Int32 ID { get; set; }
				
		
		
		/// <summary>
		/// Modello : 
		/// </summary>
		System.String  Modello  { get; set; }
		
		/// <summary>
		/// CropAggregationMacchinaID : 
		/// </summary>
		System.Int32?  CropAggregationMacchinaID  { get; set; }
		
		/// <summary>
		/// AssociationMotoreID : 
		/// </summary>
		System.Int32?  AssociationMotoreID  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _specchiettoAggregationMacchinaID
		/// </summary>	
		TList<Specchietto> SpecchiettoCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _macchinaCropAggregationMacchinaID
		/// </summary>	
		TList<Macchina> MacchinaCollection {  get;  set;}	

		#endregion Data Properties

	}
}


