using System;
using System.ComponentModel;

namespace GenTest.Entities
{
	/// <summary>
	///		The data structure representation of the 'Motore' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IMotore 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Motore"</remarks>
		System.Int32 ID { get; set; }
				
		
		
		/// <summary>
		/// Descrizione : 
		/// </summary>
		System.String  Descrizione  { get; set; }
		
		/// <summary>
		/// AggregationMotoreID : 
		/// </summary>
		System.Int32?  AggregationMotoreID  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _motoreAggregationMotoreID
		/// </summary>	
		TList<Motore> MotoreCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pistoneCompositionMotoreID
		/// </summary>	
		TList<Pistone> PistoneCollection {  get;  set;}	
	

		/// <summary>
		///	Holds a  Macchina entity object
		///	which is related to this object through the relation _macchinaAssociationMotoreID
		/// </summary>
		Macchina Macchina { get; set; }

		#endregion Data Properties

	}
}


