using System;
using System.ComponentModel;

namespace GenTest.Entities
{
	/// <summary>
	///		The data structure representation of the 'Pistone' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IPistone 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Pistone"</remarks>
		System.Int32 ID { get; set; }
				
		
		
		/// <summary>
		/// Temperatura : 
		/// </summary>
		System.Double  Temperatura  { get; set; }
		
		/// <summary>
		/// CompositionMotoreID : 
		/// </summary>
		System.Int32?  CompositionMotoreID  { get; set; }
		
		/// <summary>
		/// TrakAggregationPistoneID : 
		/// </summary>
		System.Int32?  TrakAggregationPistoneID  { get; set; }
		
		/// <summary>
		/// AggregationPistoneID : 
		/// </summary>
		System.Int32?  AggregationPistoneID  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pistoneAggregationPistoneIDGetByAggregationPistoneID
		/// </summary>	
		TList<Pistone> PistoneCollectionGetByAggregationPistoneID {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pistoneAggregationPistoneIDGetByTrakAggregationPistoneID
		/// </summary>	
		TList<Pistone> PistoneCollectionGetByTrakAggregationPistoneID {  get;  set;}	

		#endregion Data Properties

	}
}


