
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Pistone.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using GenTest.Entities.Validation;
#endregion

namespace GenTest.Entities
{
	///<summary>
	/// An object representation of the 'Pistone' table. [No description found the database]	
	///</summary>
	[Serializable, DataObject]
	[CLSCompliant(true)]
	public abstract partial class PistoneBase : EntityBase, IPistone, IEntityId<PistoneKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private PistoneEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private PistoneEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private PistoneEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Pistone> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>	
		[field:NonSerialized]
		public event PistoneEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event PistoneEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="PistoneBase"/> instance.
		///</summary>
		public PistoneBase()
		{
			this.entityData = new PistoneEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="PistoneBase"/> instance.
		///</summary>
		///<param name="_temperatura"></param>
		///<param name="_compositionMotoreID"></param>
		///<param name="_trakAggregationPistoneID"></param>
		///<param name="_aggregationPistoneID"></param>
		public PistoneBase(System.Double _temperatura, System.Int32? _compositionMotoreID, System.Int32? _trakAggregationPistoneID, 
			System.Int32? _aggregationPistoneID)
		{
			this.entityData = new PistoneEntityData();
			this.backupData = null;

			this.Temperatura = _temperatura;
			this.CompositionMotoreID = _compositionMotoreID;
			this.TrakAggregationPistoneID = _trakAggregationPistoneID;
			this.AggregationPistoneID = _aggregationPistoneID;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Pistone"/> instance.
		///</summary>
		///<param name="_temperatura"></param>
		///<param name="_compositionMotoreID"></param>
		///<param name="_trakAggregationPistoneID"></param>
		///<param name="_aggregationPistoneID"></param>
		public static Pistone CreatePistone(System.Double _temperatura, System.Int32? _compositionMotoreID, System.Int32? _trakAggregationPistoneID, 
			System.Int32? _aggregationPistoneID)
		{
			Pistone newPistone = new Pistone();
			newPistone.Temperatura = _temperatura;
			newPistone.CompositionMotoreID = _compositionMotoreID;
			newPistone.TrakAggregationPistoneID = _trakAggregationPistoneID;
			newPistone.AggregationPistoneID = _aggregationPistoneID;
			return newPistone;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Temperatura property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Double Temperatura
		{
			get
			{
				return this.entityData.Temperatura; 
			}
			
			set
			{
				if (this.entityData.Temperatura == value)
					return;
					
				OnColumnChanging(PistoneColumn.Temperatura, this.entityData.Temperatura);
				this.entityData.Temperatura = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PistoneColumn.Temperatura, this.entityData.Temperatura);
				OnPropertyChanged("Temperatura");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public override System.Int32 ID
		{
			get
			{
				return this.entityData.ID; 
			}
			
			set
			{
				if (this.entityData.ID == value)
					return;
					
				OnColumnChanging(PistoneColumn.ID, this.entityData.ID);
				this.entityData.ID = value;
				this.EntityId.ID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PistoneColumn.ID, this.entityData.ID);
				OnPropertyChanged("ID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CompositionMotoreID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsCompositionMotoreIDNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? CompositionMotoreID
		{
			get
			{
				return this.entityData.CompositionMotoreID; 
			}
			
			set
			{
				if (this.entityData.CompositionMotoreID == value)
					return;
					
				OnColumnChanging(PistoneColumn.CompositionMotoreID, this.entityData.CompositionMotoreID);
				this.entityData.CompositionMotoreID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PistoneColumn.CompositionMotoreID, this.entityData.CompositionMotoreID);
				OnPropertyChanged("CompositionMotoreID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the TrakAggregationPistoneID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsTrakAggregationPistoneIDNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? TrakAggregationPistoneID
		{
			get
			{
				return this.entityData.TrakAggregationPistoneID; 
			}
			
			set
			{
				if (this.entityData.TrakAggregationPistoneID == value)
					return;
					
				OnColumnChanging(PistoneColumn.TrakAggregationPistoneID, this.entityData.TrakAggregationPistoneID);
				this.entityData.TrakAggregationPistoneID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PistoneColumn.TrakAggregationPistoneID, this.entityData.TrakAggregationPistoneID);
				OnPropertyChanged("TrakAggregationPistoneID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AggregationPistoneID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsAggregationPistoneIDNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? AggregationPistoneID
		{
			get
			{
				return this.entityData.AggregationPistoneID; 
			}
			
			set
			{
				if (this.entityData.AggregationPistoneID == value)
					return;
					
				OnColumnChanging(PistoneColumn.AggregationPistoneID, this.entityData.AggregationPistoneID);
				this.entityData.AggregationPistoneID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(PistoneColumn.AggregationPistoneID, this.entityData.AggregationPistoneID);
				OnPropertyChanged("AggregationPistoneID");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Motore"/>.
		/// </summary>
		/// <value>The source Motore for CompositionMotoreID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Motore CompositionMotoreIDSource
      	{
            get { return entityData.CompositionMotoreIDSource; }
            set { entityData.CompositionMotoreIDSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Pistone"/>.
		/// </summary>
		/// <value>The source Pistone for TrakAggregationPistoneID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Pistone TrakAggregationPistoneIDSource
      	{
            get { return entityData.TrakAggregationPistoneIDSource; }
            set { entityData.TrakAggregationPistoneIDSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Pistone"/>.
		/// </summary>
		/// <value>The source Pistone for AggregationPistoneID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Pistone AggregationPistoneIDSource
      	{
            get { return entityData.AggregationPistoneIDSource; }
            set { entityData.AggregationPistoneIDSource = value; }
      	}
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Pistone objects
		///	which are related to this object through the relation FK_Aggregation_Pistone_Pistone
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Pistone> PistoneCollectionGetByAggregationPistoneID
		{
			get { return entityData.PistoneCollectionGetByAggregationPistoneID; }
			set { entityData.PistoneCollectionGetByAggregationPistoneID = value; }	
		}
	
		/// <summary>
		///	Holds a collection of Pistone objects
		///	which are related to this object through the relation FK_TrakAggregation_Pistone_Pistone
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Pistone> PistoneCollectionGetByTrakAggregationPistoneID
		{
			get { return entityData.PistoneCollectionGetByTrakAggregationPistoneID; }
			set { entityData.PistoneCollectionGetByTrakAggregationPistoneID = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Pistone"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Temperatura", "ID", "CompositionMotoreID", "TrakAggregationPistoneID", "AggregationPistoneID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as PistoneEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Pistone) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Pistone>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Pistone);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Pistone Entity 
		///</summary>
		protected virtual Pistone Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Pistone copy = new Pistone();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Temperatura = this.Temperatura;
				copy.ID = this.ID;
				copy.CompositionMotoreID = this.CompositionMotoreID;
				copy.TrakAggregationPistoneID = this.TrakAggregationPistoneID;
				copy.AggregationPistoneID = this.AggregationPistoneID;
			
			if (this.CompositionMotoreIDSource != null && existingCopies.Contains(this.CompositionMotoreIDSource))
				copy.CompositionMotoreIDSource = existingCopies[this.CompositionMotoreIDSource] as Motore;
			else
				copy.CompositionMotoreIDSource = MakeCopyOf(this.CompositionMotoreIDSource, existingCopies) as Motore;
			if (this.TrakAggregationPistoneIDSource != null && existingCopies.Contains(this.TrakAggregationPistoneIDSource))
				copy.TrakAggregationPistoneIDSource = existingCopies[this.TrakAggregationPistoneIDSource] as Pistone;
			else
				copy.TrakAggregationPistoneIDSource = MakeCopyOf(this.TrakAggregationPistoneIDSource, existingCopies) as Pistone;
			if (this.AggregationPistoneIDSource != null && existingCopies.Contains(this.AggregationPistoneIDSource))
				copy.AggregationPistoneIDSource = existingCopies[this.AggregationPistoneIDSource] as Pistone;
			else
				copy.AggregationPistoneIDSource = MakeCopyOf(this.AggregationPistoneIDSource, existingCopies) as Pistone;
		
			//deep copy nested objects
			copy.PistoneCollectionGetByAggregationPistoneID = (TList<Pistone>) MakeCopyOf(this.PistoneCollectionGetByAggregationPistoneID, existingCopies); 
			copy.PistoneCollectionGetByTrakAggregationPistoneID = (TList<Pistone>) MakeCopyOf(this.PistoneCollectionGetByTrakAggregationPistoneID, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Pistone Entity 
		///</summary>
		public virtual Pistone Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Pistone Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Pistone DeepCopy()
		{
			return EntityHelper.Clone<Pistone>(this as Pistone);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as PistoneEntityData;
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as PistoneEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(PistoneColumn column)
		{
			switch(column)
			{
					case PistoneColumn.Temperatura:
					return entityData.Temperatura != _originalData.Temperatura;
					case PistoneColumn.ID:
					return entityData.ID != _originalData.ID;
					case PistoneColumn.CompositionMotoreID:
					return entityData.CompositionMotoreID != _originalData.CompositionMotoreID;
					case PistoneColumn.TrakAggregationPistoneID:
					return entityData.TrakAggregationPistoneID != _originalData.TrakAggregationPistoneID;
					case PistoneColumn.AggregationPistoneID:
					return entityData.AggregationPistoneID != _originalData.AggregationPistoneID;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Temperatura != _originalData.Temperatura;
			result = result || entityData.ID != _originalData.ID;
			result = result || entityData.CompositionMotoreID != _originalData.CompositionMotoreID;
			result = result || entityData.TrakAggregationPistoneID != _originalData.TrakAggregationPistoneID;
			result = result || entityData.AggregationPistoneID != _originalData.AggregationPistoneID;
			return result;
		}	
		
		///<summary>
		///  Returns a Pistone Entity with the original data.
		///</summary>
		public Pistone GetOriginalEntity()
		{
			if (_originalData != null)
				return CreatePistone(
				_originalData.Temperatura,
				_originalData.CompositionMotoreID,
				_originalData.TrakAggregationPistoneID,
				_originalData.AggregationPistoneID
				);
				
			return (Pistone)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="PistoneBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is PistoneBase)
				return ValueEquals(this, (PistoneBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="PistoneBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Temperatura.GetHashCode() ^ 
					this.ID.GetHashCode() ^ 
					((this.CompositionMotoreID == null) ? string.Empty : this.CompositionMotoreID.ToString()).GetHashCode() ^ 
					((this.TrakAggregationPistoneID == null) ? string.Empty : this.TrakAggregationPistoneID.ToString()).GetHashCode() ^ 
					((this.AggregationPistoneID == null) ? string.Empty : this.AggregationPistoneID.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="PistoneBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(PistoneBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="PistoneBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="PistoneBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="PistoneBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(PistoneBase Object1, PistoneBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Temperatura != Object2.Temperatura)
				equal = false;
			if (Object1.ID != Object2.ID)
				equal = false;
			if ( Object1.CompositionMotoreID != null && Object2.CompositionMotoreID != null )
			{
				if (Object1.CompositionMotoreID != Object2.CompositionMotoreID)
					equal = false;
			}
			else if (Object1.CompositionMotoreID == null ^ Object2.CompositionMotoreID == null )
			{
				equal = false;
			}
			if ( Object1.TrakAggregationPistoneID != null && Object2.TrakAggregationPistoneID != null )
			{
				if (Object1.TrakAggregationPistoneID != Object2.TrakAggregationPistoneID)
					equal = false;
			}
			else if (Object1.TrakAggregationPistoneID == null ^ Object2.TrakAggregationPistoneID == null )
			{
				equal = false;
			}
			if ( Object1.AggregationPistoneID != null && Object2.AggregationPistoneID != null )
			{
				if (Object1.AggregationPistoneID != Object2.AggregationPistoneID)
					equal = false;
			}
			else if (Object1.AggregationPistoneID == null ^ Object2.AggregationPistoneID == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((PistoneBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static PistoneComparer GetComparer()
        {
            return new PistoneComparer();
        }
        */

        // Comparer delegates back to Pistone
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Pistone rhs, PistoneColumn which)
        {
            switch (which)
            {
            	
            	
            	case PistoneColumn.Temperatura:
            		return this.Temperatura.CompareTo(rhs.Temperatura);
            		
            		                 
            	
            	
            	case PistoneColumn.ID:
            		return this.ID.CompareTo(rhs.ID);
            		
            		                 
            	
            	
            	case PistoneColumn.CompositionMotoreID:
            		return this.CompositionMotoreID.Value.CompareTo(rhs.CompositionMotoreID.Value);
            		
            		                 
            	
            	
            	case PistoneColumn.TrakAggregationPistoneID:
            		return this.TrakAggregationPistoneID.Value.CompareTo(rhs.TrakAggregationPistoneID.Value);
            		
            		                 
            	
            	
            	case PistoneColumn.AggregationPistoneID:
            		return this.AggregationPistoneID.Value.CompareTo(rhs.AggregationPistoneID.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<PistoneKey> Members
		
		// member variable for the EntityId property
		private PistoneKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual PistoneKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new PistoneKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Pistone")
					.Append("|").Append( this.ID.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{6}{5}- Temperatura: {0}{5}- ID: {1}{5}- CompositionMotoreID: {2}{5}- TrakAggregationPistoneID: {3}{5}- AggregationPistoneID: {4}{5}", 
				this.Temperatura,
				this.ID,
				(this.CompositionMotoreID == null) ? string.Empty : this.CompositionMotoreID.ToString(),
				(this.TrakAggregationPistoneID == null) ? string.Empty : this.TrakAggregationPistoneID.ToString(),
				(this.AggregationPistoneID == null) ? string.Empty : this.AggregationPistoneID.ToString(),
				System.Environment.NewLine, 
				this.GetType());
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Pistone' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class PistoneEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
			/// <summary>			
			/// ID : 
			/// </summary>
			/// <remarks>Member of the primary key of the underlying table "Pistone"</remarks>
			public System.Int32 ID;
				
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Temperatura : 
		/// </summary>
		public System.Double		  Temperatura = 0.0f;
		
		/// <summary>
		/// CompositionMotoreID : 
		/// </summary>
		public System.Int32?		  CompositionMotoreID = null;
		
		/// <summary>
		/// TrakAggregationPistoneID : 
		/// </summary>
		public System.Int32?		  TrakAggregationPistoneID = null;
		
		/// <summary>
		/// AggregationPistoneID : 
		/// </summary>
		public System.Int32?		  AggregationPistoneID = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private Motore _compositionMotoreIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Motore"/>.
		/// </summary>
		/// <value>The source Motore for CompositionMotoreID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Motore CompositionMotoreIDSource
      	{
            get { return this._compositionMotoreIDSource; }
            set { this._compositionMotoreIDSource = value; }
      	}
		private Pistone _trakAggregationPistoneIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Pistone"/>.
		/// </summary>
		/// <value>The source Pistone for TrakAggregationPistoneID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Pistone TrakAggregationPistoneIDSource
      	{
            get { return this._trakAggregationPistoneIDSource; }
            set { this._trakAggregationPistoneIDSource = value; }
      	}
		private Pistone _aggregationPistoneIDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Pistone"/>.
		/// </summary>
		/// <value>The source Pistone for AggregationPistoneID.</value>
        [XmlIgnore()]
		[Browsable(false)]
		public virtual Pistone AggregationPistoneIDSource
      	{
            get { return this._aggregationPistoneIDSource; }
            set { this._aggregationPistoneIDSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region PistoneCollectionGetByAggregationPistoneID
		
		private TList<Pistone> _pistoneAggregationPistoneIDGetByAggregationPistoneID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pistoneAggregationPistoneIDGetByAggregationPistoneID
		/// </summary>	
		public TList<Pistone> PistoneCollectionGetByAggregationPistoneID
		{
			get
			{
				if (_pistoneAggregationPistoneIDGetByAggregationPistoneID == null)
				{
				_pistoneAggregationPistoneIDGetByAggregationPistoneID = new TList<Pistone>();
				}
	
				return _pistoneAggregationPistoneIDGetByAggregationPistoneID;
			}
			set { _pistoneAggregationPistoneIDGetByAggregationPistoneID = value; }
		}
		
		#endregion

		#region PistoneCollectionGetByTrakAggregationPistoneID
		
		private TList<Pistone> _pistoneAggregationPistoneIDGetByTrakAggregationPistoneID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pistoneAggregationPistoneIDGetByTrakAggregationPistoneID
		/// </summary>	
		public TList<Pistone> PistoneCollectionGetByTrakAggregationPistoneID
		{
			get
			{
				if (_pistoneAggregationPistoneIDGetByTrakAggregationPistoneID == null)
				{
				_pistoneAggregationPistoneIDGetByTrakAggregationPistoneID = new TList<Pistone>();
				}
	
				return _pistoneAggregationPistoneIDGetByTrakAggregationPistoneID;
			}
			set { _pistoneAggregationPistoneIDGetByTrakAggregationPistoneID = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			PistoneEntityData _tmp = new PistoneEntityData();
						
			_tmp.ID = this.ID;
			
			_tmp.Temperatura = this.Temperatura;
			_tmp.CompositionMotoreID = this.CompositionMotoreID;
			_tmp.TrakAggregationPistoneID = this.TrakAggregationPistoneID;
			_tmp.AggregationPistoneID = this.AggregationPistoneID;
			
			#region Source Parent Composite Entities
			if (this.CompositionMotoreIDSource != null)
				_tmp.CompositionMotoreIDSource = MakeCopyOf(this.CompositionMotoreIDSource) as Motore;
			if (this.TrakAggregationPistoneIDSource != null)
				_tmp.TrakAggregationPistoneIDSource = MakeCopyOf(this.TrakAggregationPistoneIDSource) as Pistone;
			if (this.AggregationPistoneIDSource != null)
				_tmp.AggregationPistoneIDSource = MakeCopyOf(this.AggregationPistoneIDSource) as Pistone;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._pistoneAggregationPistoneIDGetByAggregationPistoneID != null)
				_tmp.PistoneCollectionGetByAggregationPistoneID = (TList<Pistone>) MakeCopyOf(this.PistoneCollectionGetByAggregationPistoneID); 
			if (this._pistoneAggregationPistoneIDGetByTrakAggregationPistoneID != null)
				_tmp.PistoneCollectionGetByTrakAggregationPistoneID = (TList<Pistone>) MakeCopyOf(this.PistoneCollectionGetByTrakAggregationPistoneID); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			PistoneEntityData _tmp = new PistoneEntityData();
						
			_tmp.ID = this.ID;
			
			_tmp.Temperatura = this.Temperatura;
			_tmp.CompositionMotoreID = this.CompositionMotoreID;
			_tmp.TrakAggregationPistoneID = this.TrakAggregationPistoneID;
			_tmp.AggregationPistoneID = this.AggregationPistoneID;
			
			#region Source Parent Composite Entities
			if (this.CompositionMotoreIDSource != null && existingCopies.Contains(this.CompositionMotoreIDSource))
				_tmp.CompositionMotoreIDSource = existingCopies[this.CompositionMotoreIDSource] as Motore;
			else
				_tmp.CompositionMotoreIDSource = MakeCopyOf(this.CompositionMotoreIDSource, existingCopies) as Motore;
			if (this.TrakAggregationPistoneIDSource != null && existingCopies.Contains(this.TrakAggregationPistoneIDSource))
				_tmp.TrakAggregationPistoneIDSource = existingCopies[this.TrakAggregationPistoneIDSource] as Pistone;
			else
				_tmp.TrakAggregationPistoneIDSource = MakeCopyOf(this.TrakAggregationPistoneIDSource, existingCopies) as Pistone;
			if (this.AggregationPistoneIDSource != null && existingCopies.Contains(this.AggregationPistoneIDSource))
				_tmp.AggregationPistoneIDSource = existingCopies[this.AggregationPistoneIDSource] as Pistone;
			else
				_tmp.AggregationPistoneIDSource = MakeCopyOf(this.AggregationPistoneIDSource, existingCopies) as Pistone;
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.PistoneCollectionGetByAggregationPistoneID = (TList<Pistone>) MakeCopyOf(this.PistoneCollectionGetByAggregationPistoneID, existingCopies); 
			_tmp.PistoneCollectionGetByTrakAggregationPistoneID = (TList<Pistone>) MakeCopyOf(this.PistoneCollectionGetByTrakAggregationPistoneID, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PistoneColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(PistoneColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PistoneColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(PistoneColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PistoneColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(PistoneColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				PistoneEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new PistoneEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="PistoneColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(PistoneColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				PistoneEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new PistoneEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region PistoneEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Pistone"/> object.
	/// </remarks>
	public class PistoneEventArgs : System.EventArgs
	{
		private PistoneColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the PistoneEventArgs class.
		///</summary>
		public PistoneEventArgs(PistoneColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the PistoneEventArgs class.
		///</summary>
		public PistoneEventArgs(PistoneColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The PistoneColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="PistoneColumn" />
		public PistoneColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Pistone related events.
	///</summary>
	public delegate void PistoneEventHandler(object sender, PistoneEventArgs e);
	
	#region PistoneComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class PistoneComparer : System.Collections.Generic.IComparer<Pistone>
	{
		PistoneColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:PistoneComparer"/> class.
        /// </summary>
		public PistoneComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PistoneComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public PistoneComparer(PistoneColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Pistone"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Pistone"/> to compare.</param>
        /// <param name="b">The second <c>Pistone</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Pistone a, Pistone b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Pistone entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Pistone a, Pistone b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public PistoneColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region PistoneKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Pistone"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class PistoneKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the PistoneKey class.
		/// </summary>
		public PistoneKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the PistoneKey class.
		/// </summary>
		public PistoneKey(PistoneBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.ID = entity.ID;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the PistoneKey class.
		/// </summary>
		public PistoneKey(System.Int32 _iD)
		{
			#region Init Properties

			this.ID = _iD;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private PistoneBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public PistoneBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the ID property
		private System.Int32 _iD;
		
		/// <summary>
		/// Gets or sets the ID property.
		/// </summary>
		public System.Int32 ID
		{
			get { return _iD; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ID = value;
				
				_iD = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				ID = ( values["ID"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["ID"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("ID", ID);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("ID: {0}{1}",
								ID,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region PistoneColumn Enum
	
	/// <summary>
	/// Enumerate the Pistone columns.
	/// </summary>
	[Serializable]
	public enum PistoneColumn : int
	{
		/// <summary>
		/// Temperatura : 
		/// </summary>
		[EnumTextValue("Temperatura")]
		[ColumnEnum("Temperatura", typeof(System.Double), System.Data.DbType.Double, false, false, false)]
		Temperatura = 1,
		/// <summary>
		/// ID : 
		/// </summary>
		[EnumTextValue("ID")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		ID = 2,
		/// <summary>
		/// CompositionMotoreID : 
		/// </summary>
		[EnumTextValue("CompositionMotoreID")]
		[ColumnEnum("CompositionMotoreID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		CompositionMotoreID = 3,
		/// <summary>
		/// TrakAggregationPistoneID : 
		/// </summary>
		[EnumTextValue("TrakAggregationPistoneID")]
		[ColumnEnum("TrakAggregationPistoneID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		TrakAggregationPistoneID = 4,
		/// <summary>
		/// AggregationPistoneID : 
		/// </summary>
		[EnumTextValue("AggregationPistoneID")]
		[ColumnEnum("AggregationPistoneID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		AggregationPistoneID = 5
	}//End enum

	#endregion PistoneColumn Enum

} // end namespace
