//
        // BLL/BOAM [C#]
        // Business Object Avatar BellaFattura Extension
        //
        // Generated by MGen/Caffettiera
        // (C) 2008 Netical 
        //
        
        using System;
        using System.Collections;
        using System.Collections.Generic;
        using Caffettiera.CSharp.Common;
        using Caffettiera.CSharp.BLL;
        
        
        namespace GenTest.BOAM
        {
        
        public partial class BellaFattura : IBellaFatturaExt
		{
			
		}
		
        
        }
        
