//
        // BLL/BOAM [C#]
        // Business Object Avatar Fattura Extension
        //
        // Generated by MGen/Caffettiera
        // (C) 2008 Netical 
        //
        
        using System;
        using System.Collections;
        using System.Collections.Generic;
        using Caffettiera.CSharp.Common;
        using Caffettiera.CSharp.BLL;
        
        
        namespace GenTest.BOAM
        {
        
        public partial class Fattura : IFatturaExt
		{
			public void M1(ICollection<string> a)
		{
			// insert code here
		    throw new NotImplementedException("method M1 not implemented");
		    
		}
		
		}
		
        
        }
        
