//
        // BLL/BOAM [C#]
        // Business Object Avatar RigaFattura Extension
        //
        // Generated by MGen/Caffettiera
        // (C) 2008 Netical 
        //
        
        using System;
        using System.Collections;
        using System.Collections.Generic;
        using Caffettiera.CSharp.Common;
        using Caffettiera.CSharp.BLL;
        
        
        namespace GenTest.BOAM
        {
        
        public partial class RigaFattura : IRigaFatturaExt
		{
			public int Lunghezza()
		{
			// insert code here
		    throw new NotImplementedException("method Lunghezza not implemented");
		    
		}
		
		}
		
        
        }
        
